# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Solarized Light — Fish shell theme
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: solarized-light · palette: solarized-light · variant: base
# Conformance: FIDELITY PALETTE (§11.5) — reproduced verbatim, NON-CONFORMING, not adoptable as a project palette
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

# Syntax-highlighting colours
set -g fish_color_normal 657B83
set -g fish_color_command 859900
set -g fish_color_keyword 268BD2
set -g fish_color_quote 657B83
set -g fish_color_redirection 2AA198
set -g fish_color_end 6C71C4
set -g fish_color_error DC322F
set -g fish_color_param 6C71C4
set -g fish_color_comment 6C71C4
set -g fish_color_selection --background=EEE8D5
set -g fish_color_search_match --background=EEE8D5
set -g fish_color_operator 859900
set -g fish_color_escape 2AA198
set -g fish_color_autosuggestion 6C71C4
set -g fish_color_cancel DC322F
set -g fish_color_valid_path 6C71C4 --underline

# Tab-completion pager colours
set -g fish_pager_color_prefix 2AA198
set -g fish_pager_color_completion 657B83
set -g fish_pager_color_description 6C71C4
set -g fish_pager_color_progress 859900

# The prompt function
function fish_prompt
    set -l last_status $status

    # Working directory
    set_color 6C71C4
    printf '%s' (prompt_pwd)
    set_color normal

    # Git branch, if any
    if type -q git
        set -l branch (git branch --show-current 2>/dev/null)
        if test -n "$branch"
            set_color 268BD2
            printf ' on  %s' $branch
            set_color normal
        end
    end

    # Status symbol
    if test $last_status -eq 0
        set_color 859900
    else
        set_color DC322F
    end
    printf ' ❯ '
    set_color normal
end
