# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore Blue High Contrast — Fish shell theme
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore-blue-high-contrast · palette: steelbore-blue · variant: high-contrast (§11.1.1 accessible-mode sibling)
# Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

# Syntax-highlighting colours
set -g fish_color_normal E6F0FF
set -g fish_color_command 28C76F
set -g fish_color_keyword 79B4FF
set -g fish_color_quote E6F0FF
set -g fish_color_redirection FF8A4B
set -g fish_color_end 66A3FF
set -g fish_color_error FF8F8F
set -g fish_color_param 66A3FF
set -g fish_color_comment 66A3FF
set -g fish_color_selection --background=0F1728
set -g fish_color_search_match --background=0F1728
set -g fish_color_operator 28C76F
set -g fish_color_escape FF8A4B
set -g fish_color_autosuggestion 66A3FF
set -g fish_color_cancel FF8F8F
set -g fish_color_valid_path 66A3FF --underline

# Tab-completion pager colours
set -g fish_pager_color_prefix FF8A4B
set -g fish_pager_color_completion E6F0FF
set -g fish_pager_color_description 66A3FF
set -g fish_pager_color_progress 28C76F

# The prompt function
function fish_prompt
    set -l last_status $status

    # Working directory
    set_color 66A3FF
    printf '%s' (prompt_pwd)
    set_color normal

    # Git branch, if any
    if type -q git
        set -l branch (git branch --show-current 2>/dev/null)
        if test -n "$branch"
            set_color 79B4FF
            printf ' on  %s' $branch
            set_color normal
        end
    end

    # Status symbol
    if test $last_status -eq 0
        set_color 28C76F
    else
        set_color FF8F8F
    end
    printf ' ❯ '
    set_color normal
end
