# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore Classic High Contrast — Fish shell theme
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore-classic-high-contrast · palette: steelbore-classic · variant: high-contrast (§11.1.1 accessible-mode sibling)
# Conformance: legacy six-role contract (§11.2); measured against Void Navy
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

# Syntax-highlighting colours
set -g fish_color_normal D98E32
set -g fish_color_command 50FA7B
set -g fish_color_keyword 7FAEDC
set -g fish_color_quote D98E32
set -g fish_color_redirection 8BE9FD
set -g fish_color_end 7FAEDC
set -g fish_color_error FF8080
set -g fish_color_param 7FAEDC
set -g fish_color_comment 7FAEDC
set -g fish_color_selection --background=000027
set -g fish_color_search_match --background=000027
set -g fish_color_operator 50FA7B
set -g fish_color_escape 8BE9FD
set -g fish_color_autosuggestion 7FAEDC
set -g fish_color_cancel FF8080
set -g fish_color_valid_path 7FAEDC --underline

# Tab-completion pager colours
set -g fish_pager_color_prefix 8BE9FD
set -g fish_pager_color_completion D98E32
set -g fish_pager_color_description 7FAEDC
set -g fish_pager_color_progress 50FA7B

# The prompt function
function fish_prompt
    set -l last_status $status

    # Working directory
    set_color 7FAEDC
    printf '%s' (prompt_pwd)
    set_color normal

    # Git branch, if any
    if type -q git
        set -l branch (git branch --show-current 2>/dev/null)
        if test -n "$branch"
            set_color 7FAEDC
            printf ' on  %s' $branch
            set_color normal
        end
    end

    # Status symbol
    if test $last_status -eq 0
        set_color 50FA7B
    else
        set_color FF8080
    end
    printf ' ❯ '
    set_color normal
end
