# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore Mono — Fish shell theme
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore-mono · palette: steelbore-mono · variant: mono (§11.1.1, 4-bit ANSI, NO_COLOR)
# Conformance: palette-independent; defers hue to the terminal (§11.1.1)
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

# Syntax-highlighting colours
set -g fish_color_normal normal
set -g fish_color_command green
set -g fish_color_keyword brwhite
set -g fish_color_quote normal
set -g fish_color_redirection normal --reverse
set -g fish_color_end blue
set -g fish_color_error red
set -g fish_color_param blue
set -g fish_color_comment blue
set -g fish_color_selection --background=normal
set -g fish_color_search_match --background=normal
set -g fish_color_operator green
set -g fish_color_escape normal --reverse
set -g fish_color_autosuggestion blue
set -g fish_color_cancel red
set -g fish_color_valid_path blue --underline

# Tab-completion pager colours
set -g fish_pager_color_prefix normal --reverse
set -g fish_pager_color_completion normal
set -g fish_pager_color_description blue
set -g fish_pager_color_progress green

# The prompt function
function fish_prompt
    set -l last_status $status

    # Working directory
    set_color blue
    printf '%s' (prompt_pwd)
    set_color normal

    # Git branch, if any
    if type -q git
        set -l branch (git branch --show-current 2>/dev/null)
        if test -n "$branch"
            set_color brwhite
            printf ' on  %s' $branch
            set_color normal
        end
    end

    # Status symbol
    if test $last_status -eq 0
        set_color green
    else
        set_color red
    end
    printf ' ❯ '
    set_color normal
end
