# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore Magnetar — Fish shell theme
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore-magnetar · palette: steelbore-magnetar · variant: base
# Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

# Syntax-highlighting colours
set -g fish_color_normal FFFFFF
set -g fish_color_command 5BE49B
set -g fish_color_keyword E445FF
set -g fish_color_quote FFFFFF
set -g fish_color_redirection FDBBFF
set -g fish_color_end FC8AFF
set -g fish_color_error FF6B6B
set -g fish_color_param FC8AFF
set -g fish_color_comment FC8AFF
set -g fish_color_selection --background=1E1E22
set -g fish_color_search_match --background=1E1E22
set -g fish_color_operator 5BE49B
set -g fish_color_escape FDBBFF
set -g fish_color_autosuggestion FC8AFF
set -g fish_color_cancel FF6B6B
set -g fish_color_valid_path FC8AFF --underline

# Tab-completion pager colours
set -g fish_pager_color_prefix FDBBFF
set -g fish_pager_color_completion FFFFFF
set -g fish_pager_color_description FC8AFF
set -g fish_pager_color_progress 5BE49B

# The prompt function
function fish_prompt
    set -l last_status $status

    # Working directory
    set_color FC8AFF
    printf '%s' (prompt_pwd)
    set_color normal

    # Git branch, if any
    if type -q git
        set -l branch (git branch --show-current 2>/dev/null)
        if test -n "$branch"
            set_color E445FF
            printf ' on  %s' $branch
            set_color normal
        end
    end

    # Status symbol
    if test $last_status -eq 0
        set_color 5BE49B
    else
        set_color FF6B6B
    end
    printf ' ❯ '
    set_color normal
end
