# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore NavyWhite — Fish shell theme
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore-navywhite · palette: steelbore-navywhite · variant: base
# Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

# Syntax-highlighting colours
set -g fish_color_normal 111827
set -g fish_color_command 2A6349
set -g fish_color_keyword 2A5580
set -g fish_color_quote 111827
set -g fish_color_redirection 2A5580
set -g fish_color_end 1C2433
set -g fish_color_error 93211F
set -g fish_color_param 1C2433
set -g fish_color_comment 1C2433
set -g fish_color_selection --background=F4F3F1
set -g fish_color_search_match --background=F4F3F1
set -g fish_color_operator 2A6349
set -g fish_color_escape 2A5580
set -g fish_color_autosuggestion 1C2433
set -g fish_color_cancel 93211F
set -g fish_color_valid_path 1C2433 --underline

# Tab-completion pager colours
set -g fish_pager_color_prefix 2A5580
set -g fish_pager_color_completion 111827
set -g fish_pager_color_description 1C2433
set -g fish_pager_color_progress 2A6349

# The prompt function
function fish_prompt
    set -l last_status $status

    # Working directory
    set_color 1C2433
    printf '%s' (prompt_pwd)
    set_color normal

    # Git branch, if any
    if type -q git
        set -l branch (git branch --show-current 2>/dev/null)
        if test -n "$branch"
            set_color 2A5580
            printf ' on  %s' $branch
            set_color normal
        end
    end

    # Status symbol
    if test $last_status -eq 0
        set_color 2A6349
    else
        set_color 93211F
    end
    printf ' ❯ '
    set_color normal
end
