# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore Green Alt — Fish shell theme
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore-greenalt · palette: steelbore-greenalt · variant: base
# Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

# Syntax-highlighting colours
set -g fish_color_normal D7F5E0
set -g fish_color_command 00AD15
set -g fish_color_keyword 00FF41
set -g fish_color_quote D7F5E0
set -g fish_color_redirection 00FF41
set -g fish_color_end 1CA152
set -g fish_color_error FF6B6B
set -g fish_color_param 1CA152
set -g fish_color_comment 1CA152
set -g fish_color_selection --background=08180C
set -g fish_color_search_match --background=08180C
set -g fish_color_operator 00AD15
set -g fish_color_escape 00FF41
set -g fish_color_autosuggestion 1CA152
set -g fish_color_cancel FF6B6B
set -g fish_color_valid_path 1CA152 --underline

# Tab-completion pager colours
set -g fish_pager_color_prefix 00FF41
set -g fish_pager_color_completion D7F5E0
set -g fish_pager_color_description 1CA152
set -g fish_pager_color_progress 00AD15

# The prompt function
function fish_prompt
    set -l last_status $status

    # Working directory
    set_color 1CA152
    printf '%s' (prompt_pwd)
    set_color normal

    # Git branch, if any
    if type -q git
        set -l branch (git branch --show-current 2>/dev/null)
        if test -n "$branch"
            set_color 00FF41
            printf ' on  %s' $branch
            set_color normal
        end
    end

    # Status symbol
    if test $last_status -eq 0
        set_color 00AD15
    else
        set_color FF6B6B
    end
    printf ' ❯ '
    set_color normal
end
