# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore Biolume — Fish shell theme
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore-biolume · palette: steelbore-biolume · variant: base
# Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

# Syntax-highlighting colours
set -g fish_color_normal C7D2D9
set -g fish_color_command 00B39A
set -g fish_color_keyword B6FF3B
set -g fish_color_quote C7D2D9
set -g fish_color_redirection B6FF3B
set -g fish_color_end 00F0FF
set -g fish_color_error FF6B6B
set -g fish_color_param 00F0FF
set -g fish_color_comment 00F0FF
set -g fish_color_selection --background=1B2630
set -g fish_color_search_match --background=1B2630
set -g fish_color_operator 00B39A
set -g fish_color_escape B6FF3B
set -g fish_color_autosuggestion 00F0FF
set -g fish_color_cancel FF6B6B
set -g fish_color_valid_path 00F0FF --underline

# Tab-completion pager colours
set -g fish_pager_color_prefix B6FF3B
set -g fish_pager_color_completion C7D2D9
set -g fish_pager_color_description 00F0FF
set -g fish_pager_color_progress 00B39A

# The prompt function
function fish_prompt
    set -l last_status $status

    # Working directory
    set_color 00F0FF
    printf '%s' (prompt_pwd)
    set_color normal

    # Git branch, if any
    if type -q git
        set -l branch (git branch --show-current 2>/dev/null)
        if test -n "$branch"
            set_color B6FF3B
            printf ' on  %s' $branch
            set_color normal
        end
    end

    # Status symbol
    if test $last_status -eq 0
        set_color 00B39A
    else
        set_color FF6B6B
    end
    printf ' ❯ '
    set_color normal
end
