# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore High Contrast — Fish shell theme
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore-high-contrast · palette: steelbore · variant: high-contrast (§11.1.1 accessible-mode sibling)
# Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

# Syntax-highlighting colours
set -g fish_color_normal D9DEE5
set -g fish_color_command B4FF00
set -g fish_color_keyword FF8A3D
set -g fish_color_quote D9DEE5
set -g fish_color_redirection B4FF00
set -g fish_color_end B3A1FF
set -g fish_color_error FF7A7A
set -g fish_color_param B3A1FF
set -g fish_color_comment B3A1FF
set -g fish_color_selection --background=0E2A47
set -g fish_color_search_match --background=0E2A47
set -g fish_color_operator B4FF00
set -g fish_color_escape B4FF00
set -g fish_color_autosuggestion B3A1FF
set -g fish_color_cancel FF7A7A
set -g fish_color_valid_path B3A1FF --underline

# Tab-completion pager colours
set -g fish_pager_color_prefix B4FF00
set -g fish_pager_color_completion D9DEE5
set -g fish_pager_color_description B3A1FF
set -g fish_pager_color_progress B4FF00

# The prompt function
function fish_prompt
    set -l last_status $status

    # Working directory
    set_color B3A1FF
    printf '%s' (prompt_pwd)
    set_color normal

    # Git branch, if any
    if type -q git
        set -l branch (git branch --show-current 2>/dev/null)
        if test -n "$branch"
            set_color FF8A3D
            printf ' on  %s' $branch
            set_color normal
        end
    end

    # Status symbol
    if test $last_status -eq 0
        set_color B4FF00
    else
        set_color FF7A7A
    end
    printf ' ❯ '
    set_color normal
end
