# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore Green High Contrast — Fish shell theme
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore-green-high-contrast · palette: steelbore-green · variant: high-contrast (§11.1.1 accessible-mode sibling)
# Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

# Syntax-highlighting colours
set -g fish_color_normal 00FF41
set -g fish_color_command 00B81C
set -g fish_color_keyword E8FFF0
set -g fish_color_quote 00FF41
set -g fish_color_redirection E8FFF0
set -g fish_color_end 25B85F
set -g fish_color_error FF6B6B
set -g fish_color_param 25B85F
set -g fish_color_comment 25B85F
set -g fish_color_selection --background=08180C
set -g fish_color_search_match --background=08180C
set -g fish_color_operator 00B81C
set -g fish_color_escape E8FFF0
set -g fish_color_autosuggestion 25B85F
set -g fish_color_cancel FF6B6B
set -g fish_color_valid_path 25B85F --underline

# Tab-completion pager colours
set -g fish_pager_color_prefix E8FFF0
set -g fish_pager_color_completion 00FF41
set -g fish_pager_color_description 25B85F
set -g fish_pager_color_progress 00B81C

# The prompt function
function fish_prompt
    set -l last_status $status

    # Working directory
    set_color 25B85F
    printf '%s' (prompt_pwd)
    set_color normal

    # Git branch, if any
    if type -q git
        set -l branch (git branch --show-current 2>/dev/null)
        if test -n "$branch"
            set_color E8FFF0
            printf ' on  %s' $branch
            set_color normal
        end
    end

    # Status symbol
    if test $last_status -eq 0
        set_color 00B81C
    else
        set_color FF6B6B
    end
    printf ' ❯ '
    set_color normal
end
