# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore Hanzo Steel — Fish shell theme
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore-hanzosteel · palette: steelbore-hanzosteel · variant: base
# Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

# Syntax-highlighting colours
set -g fish_color_normal F5F0E6
set -g fish_color_command 5BE49B
set -g fish_color_keyword FCD612
set -g fish_color_quote F5F0E6
set -g fish_color_redirection FCD612
set -g fish_color_end F4B900
set -g fish_color_error F04A44
set -g fish_color_param F4B900
set -g fish_color_comment F4B900
set -g fish_color_selection --background=1C1811
set -g fish_color_search_match --background=1C1811
set -g fish_color_operator 5BE49B
set -g fish_color_escape FCD612
set -g fish_color_autosuggestion F4B900
set -g fish_color_cancel F04A44
set -g fish_color_valid_path F4B900 --underline

# Tab-completion pager colours
set -g fish_pager_color_prefix FCD612
set -g fish_pager_color_completion F5F0E6
set -g fish_pager_color_description F4B900
set -g fish_pager_color_progress 5BE49B

# The prompt function
function fish_prompt
    set -l last_status $status

    # Working directory
    set_color F4B900
    printf '%s' (prompt_pwd)
    set_color normal

    # Git branch, if any
    if type -q git
        set -l branch (git branch --show-current 2>/dev/null)
        if test -n "$branch"
            set_color FCD612
            printf ' on  %s' $branch
            set_color normal
        end
    end

    # Status symbol
    if test $last_status -eq 0
        set_color 5BE49B
    else
        set_color F04A44
    end
    printf ' ❯ '
    set_color normal
end
