# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Tokyo Night — Fish shell theme
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: tokyonight · palette: tokyonight · variant: base
# Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

# Syntax-highlighting colours
set -g fish_color_normal C0CAF5
set -g fish_color_command 9ECE6A
set -g fish_color_keyword 7AA2F7
set -g fish_color_quote C0CAF5
set -g fish_color_redirection 7DCFFF
set -g fish_color_end BB9AF7
set -g fish_color_error F7768E
set -g fish_color_param BB9AF7
set -g fish_color_comment BB9AF7
set -g fish_color_selection --background=24283B
set -g fish_color_search_match --background=24283B
set -g fish_color_operator 9ECE6A
set -g fish_color_escape 7DCFFF
set -g fish_color_autosuggestion BB9AF7
set -g fish_color_cancel F7768E
set -g fish_color_valid_path BB9AF7 --underline

# Tab-completion pager colours
set -g fish_pager_color_prefix 7DCFFF
set -g fish_pager_color_completion C0CAF5
set -g fish_pager_color_description BB9AF7
set -g fish_pager_color_progress 9ECE6A

# The prompt function
function fish_prompt
    set -l last_status $status

    # Working directory
    set_color BB9AF7
    printf '%s' (prompt_pwd)
    set_color normal

    # Git branch, if any
    if type -q git
        set -l branch (git branch --show-current 2>/dev/null)
        if test -n "$branch"
            set_color 7AA2F7
            printf ' on  %s' $branch
            set_color normal
        end
    end

    # Status symbol
    if test $last_status -eq 0
        set_color 9ECE6A
    else
        set_color F7768E
    end
    printf ' ❯ '
    set_color normal
end
