# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore High Contrast — Bash prompt theme
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore-high-contrast · palette: steelbore · variant: high-contrast (§11.1.1 accessible-mode sibling)
# Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

# Sourced from ~/.bashrc -- not executed directly, so no shebang.
# Installs a PROMPT_COMMAND that colours PS1 from this theme's
# structure / accent / success / error roles (Steelbore Standard
# Sec. 11.1). Prompt-only: no LS_COLORS export, nothing else sourced.

spacecraft_software_prompt() {
    local EXIT_CODE=$?

    local C_RESET="\[\e[0m\]"
    local C_DIR="\[\e[38;2;179;161;255m\]"
    local C_GIT="\[\e[38;2;255;138;61m\]"
    local C_SUCCESS="\[\e[38;2;180;255;0m\]"
    local C_FAIL="\[\e[38;2;255;122;122m\]"

    local GIT_BRANCH=""
    if git rev-parse --is-inside-work-tree &>/dev/null; then
        GIT_BRANCH=$(git symbolic-ref --short HEAD 2>/dev/null || git describe --tags --always 2>/dev/null)
        GIT_BRANCH=" ${C_GIT}on  ${GIT_BRANCH}"
    fi

    local STATUS_SYMBOL="❯"
    local STATUS_COLOR=$C_SUCCESS
    if [ $EXIT_CODE -ne 0 ]; then
        STATUS_COLOR=$C_FAIL
    fi

    PS1="${C_DIR}\w${GIT_BRANCH} ${STATUS_COLOR}${STATUS_SYMBOL} ${C_RESET}"
}

PROMPT_COMMAND=spacecraft_software_prompt
