# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Solarized Dark — Nushell colour-config module
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: solarized-dark · palette: solarized-dark · variant: base
# Conformance: FIDELITY PALETTE (§11.5) — reproduced verbatim, NON-CONFORMING, not adoptable as a project palette
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/
# Save under themes/ and source it, or point SPACECRAFT_THEME at its
# slug — see INSTALL.md.

export def main [] {
    return {
        separator: "#6C71C4"
        leading_trailing_space_bg: "#073642"
        empty: "#6C71C4"
        int: "#B58900"
        filesize: "#2AA198"
        duration: "#B58900"
        date: "#6C71C4"
        range: "#B58900"
        float: "#B58900"
        string: "#839496"
        nothing: "#6C71C4"
        binary: "#6C71C4"
        cellpath: "#839496"
        record: "#6C71C4"
        list: "#6C71C4"
        block: "#6C71C4"
        hints: "#6C71C4"
        header: { fg: "#859900" attr: "b" }
        row_index: { fg: "#859900" attr: "b" }
        bool: { || if $in { "#859900" } else { "#DC322F" } }
        search_result: { fg: "#002B36" bg: "#268BD2" }
        shape_and: "#6C71C4"
        shape_or: "#6C71C4"
        shape_binary: "#6C71C4"
        shape_block: "#6C71C4"
        shape_bool: "#268BD2"
        shape_closure: "#6C71C4"
        shape_custom: "#2AA198"
        shape_datetime: "#6C71C4"
        shape_directory: "#2AA198"
        shape_external: "#839496"
        shape_external_resolved: "#859900"
        shape_externalarg: "#839496"
        shape_filepath: "#2AA198"
        shape_flag: "#6C71C4"
        shape_float: "#B58900"
        shape_globpattern: "#2AA198"
        shape_int: "#B58900"
        shape_internalcall: "#2AA198"
        shape_keyword: "#268BD2"
        shape_list: "#6C71C4"
        shape_literal: "#6C71C4"
        shape_match_pattern: "#268BD2"
        shape_matching_brackets: "#2AA198"
        shape_nothing: "#6C71C4"
        shape_operator: "#6C71C4"
        shape_pipe: "#6C71C4"
        shape_range: "#B58900"
        shape_record: "#6C71C4"
        shape_redirection: "#6C71C4"
        shape_signature: "#2AA198"
        shape_string: "#859900"
        shape_string_interpolation: "#859900"
        shape_table: "#6C71C4"
        shape_variable: "#268BD2"
        shape_vardecl: "#268BD2"
        shape_raw_string: "#859900"
        shape_garbage: { fg: "#002B36" bg: "#DC322F" attr: "b" }
    }
}
