# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore Magnetar — Nushell colour-config module
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore-magnetar · palette: steelbore-magnetar · variant: base
# Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/
# Save under themes/ and source it, or point SPACECRAFT_THEME at its
# slug — see INSTALL.md.

export def main [] {
    return {
        separator: "#FC8AFF"
        leading_trailing_space_bg: "#1E1E22"
        empty: "#FC8AFF"
        int: "#FFC857"
        filesize: "#FDBBFF"
        duration: "#FFC857"
        date: "#FC8AFF"
        range: "#FFC857"
        float: "#FFC857"
        string: "#FFFFFF"
        nothing: "#FC8AFF"
        binary: "#FC8AFF"
        cellpath: "#FFFFFF"
        record: "#FC8AFF"
        list: "#FC8AFF"
        block: "#FC8AFF"
        hints: "#FC8AFF"
        header: { fg: "#5BE49B" attr: "b" }
        row_index: { fg: "#5BE49B" attr: "b" }
        bool: { || if $in { "#5BE49B" } else { "#FF6B6B" } }
        search_result: { fg: "#141418" bg: "#E445FF" }
        shape_and: "#FC8AFF"
        shape_or: "#FC8AFF"
        shape_binary: "#FC8AFF"
        shape_block: "#FC8AFF"
        shape_bool: "#E445FF"
        shape_closure: "#FC8AFF"
        shape_custom: "#FDBBFF"
        shape_datetime: "#FC8AFF"
        shape_directory: "#FDBBFF"
        shape_external: "#FFFFFF"
        shape_external_resolved: "#5BE49B"
        shape_externalarg: "#FFFFFF"
        shape_filepath: "#FDBBFF"
        shape_flag: "#FC8AFF"
        shape_float: "#FFC857"
        shape_globpattern: "#FDBBFF"
        shape_int: "#FFC857"
        shape_internalcall: "#FDBBFF"
        shape_keyword: "#E445FF"
        shape_list: "#FC8AFF"
        shape_literal: "#FC8AFF"
        shape_match_pattern: "#E445FF"
        shape_matching_brackets: "#FDBBFF"
        shape_nothing: "#FC8AFF"
        shape_operator: "#FC8AFF"
        shape_pipe: "#FC8AFF"
        shape_range: "#FFC857"
        shape_record: "#FC8AFF"
        shape_redirection: "#FC8AFF"
        shape_signature: "#FDBBFF"
        shape_string: "#5BE49B"
        shape_string_interpolation: "#5BE49B"
        shape_table: "#FC8AFF"
        shape_variable: "#E445FF"
        shape_vardecl: "#E445FF"
        shape_raw_string: "#5BE49B"
        shape_garbage: { fg: "#141418" bg: "#FF6B6B" attr: "b" }
    }
}
