# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore — Nushell colour-config module
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore · palette: steelbore · variant: base
# Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/
# Save under themes/ and source it, or point SPACECRAFT_THEME at its
# slug — see INSTALL.md.

export def main [] {
    return {
        separator: "#8A6CFF"
        leading_trailing_space_bg: "#0E2A47"
        empty: "#8A6CFF"
        int: "#E445FF"
        filesize: "#B4FF00"
        duration: "#E445FF"
        date: "#8A6CFF"
        range: "#E445FF"
        float: "#E445FF"
        string: "#D9DEE5"
        nothing: "#8A6CFF"
        binary: "#8A6CFF"
        cellpath: "#D9DEE5"
        record: "#8A6CFF"
        list: "#8A6CFF"
        block: "#8A6CFF"
        hints: "#8A6CFF"
        header: { fg: "#B4FF00" attr: "b" }
        row_index: { fg: "#B4FF00" attr: "b" }
        bool: { || if $in { "#B4FF00" } else { "#FF3B3B" } }
        search_result: { fg: "#000027" bg: "#FF5E00" }
        shape_and: "#8A6CFF"
        shape_or: "#8A6CFF"
        shape_binary: "#8A6CFF"
        shape_block: "#8A6CFF"
        shape_bool: "#FF5E00"
        shape_closure: "#8A6CFF"
        shape_custom: "#B4FF00"
        shape_datetime: "#8A6CFF"
        shape_directory: "#B4FF00"
        shape_external: "#D9DEE5"
        shape_external_resolved: "#B4FF00"
        shape_externalarg: "#D9DEE5"
        shape_filepath: "#B4FF00"
        shape_flag: "#8A6CFF"
        shape_float: "#E445FF"
        shape_globpattern: "#B4FF00"
        shape_int: "#E445FF"
        shape_internalcall: "#B4FF00"
        shape_keyword: "#FF5E00"
        shape_list: "#8A6CFF"
        shape_literal: "#8A6CFF"
        shape_match_pattern: "#FF5E00"
        shape_matching_brackets: "#B4FF00"
        shape_nothing: "#8A6CFF"
        shape_operator: "#8A6CFF"
        shape_pipe: "#8A6CFF"
        shape_range: "#E445FF"
        shape_record: "#8A6CFF"
        shape_redirection: "#8A6CFF"
        shape_signature: "#B4FF00"
        shape_string: "#B4FF00"
        shape_string_interpolation: "#B4FF00"
        shape_table: "#8A6CFF"
        shape_variable: "#FF5E00"
        shape_vardecl: "#FF5E00"
        shape_raw_string: "#B4FF00"
        shape_garbage: { fg: "#000027" bg: "#FF3B3B" attr: "b" }
    }
}
