# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore NavyWhite High Contrast — Nushell colour-config module
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore-navywhite-high-contrast · palette: steelbore-navywhite · variant: high-contrast (§11.1.1 accessible-mode sibling)
# Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/
# Save under themes/ and source it, or point SPACECRAFT_THEME at its
# slug — see INSTALL.md.

export def main [] {
    return {
        separator: "#1C2433"
        leading_trailing_space_bg: "#F4F3F1"
        empty: "#1C2433"
        int: "#5A3F09"
        filesize: "#1F4A73"
        duration: "#5A3F09"
        date: "#1C2433"
        range: "#5A3F09"
        float: "#5A3F09"
        string: "#111827"
        nothing: "#1C2433"
        binary: "#1C2433"
        cellpath: "#111827"
        record: "#1C2433"
        list: "#1C2433"
        block: "#1C2433"
        hints: "#1C2433"
        header: { fg: "#16452F" attr: "b" }
        row_index: { fg: "#16452F" attr: "b" }
        bool: { || if $in { "#16452F" } else { "#7E1C1A" } }
        search_result: { fg: "#E7E5E0" bg: "#1F4A73" }
        shape_and: "#1C2433"
        shape_or: "#1C2433"
        shape_binary: "#1C2433"
        shape_block: "#1C2433"
        shape_bool: "#1F4A73"
        shape_closure: "#1C2433"
        shape_custom: "#1F4A73"
        shape_datetime: "#1C2433"
        shape_directory: "#1F4A73"
        shape_external: "#111827"
        shape_external_resolved: "#16452F"
        shape_externalarg: "#111827"
        shape_filepath: "#1F4A73"
        shape_flag: "#1C2433"
        shape_float: "#5A3F09"
        shape_globpattern: "#1F4A73"
        shape_int: "#5A3F09"
        shape_internalcall: "#1F4A73"
        shape_keyword: "#1F4A73"
        shape_list: "#1C2433"
        shape_literal: "#1C2433"
        shape_match_pattern: "#1F4A73"
        shape_matching_brackets: "#1F4A73"
        shape_nothing: "#1C2433"
        shape_operator: "#1C2433"
        shape_pipe: "#1C2433"
        shape_range: "#5A3F09"
        shape_record: "#1C2433"
        shape_redirection: "#1C2433"
        shape_signature: "#1F4A73"
        shape_string: "#16452F"
        shape_string_interpolation: "#16452F"
        shape_table: "#1C2433"
        shape_variable: "#1F4A73"
        shape_vardecl: "#1F4A73"
        shape_raw_string: "#16452F"
        shape_garbage: { fg: "#E7E5E0" bg: "#7E1C1A" attr: "b" }
    }
}
