# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore Green Alt — Nushell colour-config module
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore-greenalt · palette: steelbore-greenalt · variant: base
# Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/
# Save under themes/ and source it, or point SPACECRAFT_THEME at its
# slug — see INSTALL.md.

export def main [] {
    return {
        separator: "#1CA152"
        leading_trailing_space_bg: "#08180C"
        empty: "#1CA152"
        int: "#FFC857"
        filesize: "#00FF41"
        duration: "#FFC857"
        date: "#1CA152"
        range: "#FFC857"
        float: "#FFC857"
        string: "#D7F5E0"
        nothing: "#1CA152"
        binary: "#1CA152"
        cellpath: "#D7F5E0"
        record: "#1CA152"
        list: "#1CA152"
        block: "#1CA152"
        hints: "#1CA152"
        header: { fg: "#00AD15" attr: "b" }
        row_index: { fg: "#00AD15" attr: "b" }
        bool: { || if $in { "#00AD15" } else { "#FF6B6B" } }
        search_result: { fg: "#0D0208" bg: "#00FF41" }
        shape_and: "#1CA152"
        shape_or: "#1CA152"
        shape_binary: "#1CA152"
        shape_block: "#1CA152"
        shape_bool: "#00FF41"
        shape_closure: "#1CA152"
        shape_custom: "#00FF41"
        shape_datetime: "#1CA152"
        shape_directory: "#00FF41"
        shape_external: "#D7F5E0"
        shape_external_resolved: "#00AD15"
        shape_externalarg: "#D7F5E0"
        shape_filepath: "#00FF41"
        shape_flag: "#1CA152"
        shape_float: "#FFC857"
        shape_globpattern: "#00FF41"
        shape_int: "#FFC857"
        shape_internalcall: "#00FF41"
        shape_keyword: "#00FF41"
        shape_list: "#1CA152"
        shape_literal: "#1CA152"
        shape_match_pattern: "#00FF41"
        shape_matching_brackets: "#00FF41"
        shape_nothing: "#1CA152"
        shape_operator: "#1CA152"
        shape_pipe: "#1CA152"
        shape_range: "#FFC857"
        shape_record: "#1CA152"
        shape_redirection: "#1CA152"
        shape_signature: "#00FF41"
        shape_string: "#00AD15"
        shape_string_interpolation: "#00AD15"
        shape_table: "#1CA152"
        shape_variable: "#00FF41"
        shape_vardecl: "#00FF41"
        shape_raw_string: "#00AD15"
        shape_garbage: { fg: "#0D0208" bg: "#FF6B6B" attr: "b" }
    }
}
