# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore Blue — Nushell colour-config module
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore-blue · palette: steelbore-blue · variant: base
# Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/
# Save under themes/ and source it, or point SPACECRAFT_THEME at its
# slug — see INSTALL.md.

export def main [] {
    return {
        separator: "#3390FF"
        leading_trailing_space_bg: "#0F1728"
        empty: "#3390FF"
        int: "#FFC857"
        filesize: "#FF8A4B"
        duration: "#FFC857"
        date: "#3390FF"
        range: "#FFC857"
        float: "#FFC857"
        string: "#E6F0FF"
        nothing: "#3390FF"
        binary: "#3390FF"
        cellpath: "#E6F0FF"
        record: "#3390FF"
        list: "#3390FF"
        block: "#3390FF"
        hints: "#3390FF"
        header: { fg: "#28C76F" attr: "b" }
        row_index: { fg: "#28C76F" attr: "b" }
        bool: { || if $in { "#28C76F" } else { "#FF6B6B" } }
        search_result: { fg: "#0A1024" bg: "#3390FF" }
        shape_and: "#3390FF"
        shape_or: "#3390FF"
        shape_binary: "#3390FF"
        shape_block: "#3390FF"
        shape_bool: "#3390FF"
        shape_closure: "#3390FF"
        shape_custom: "#FF8A4B"
        shape_datetime: "#3390FF"
        shape_directory: "#FF8A4B"
        shape_external: "#E6F0FF"
        shape_external_resolved: "#28C76F"
        shape_externalarg: "#E6F0FF"
        shape_filepath: "#FF8A4B"
        shape_flag: "#3390FF"
        shape_float: "#FFC857"
        shape_globpattern: "#FF8A4B"
        shape_int: "#FFC857"
        shape_internalcall: "#FF8A4B"
        shape_keyword: "#3390FF"
        shape_list: "#3390FF"
        shape_literal: "#3390FF"
        shape_match_pattern: "#3390FF"
        shape_matching_brackets: "#FF8A4B"
        shape_nothing: "#3390FF"
        shape_operator: "#3390FF"
        shape_pipe: "#3390FF"
        shape_range: "#FFC857"
        shape_record: "#3390FF"
        shape_redirection: "#3390FF"
        shape_signature: "#FF8A4B"
        shape_string: "#28C76F"
        shape_string_interpolation: "#28C76F"
        shape_table: "#3390FF"
        shape_variable: "#3390FF"
        shape_vardecl: "#3390FF"
        shape_raw_string: "#28C76F"
        shape_garbage: { fg: "#0A1024" bg: "#FF6B6B" attr: "b" }
    }
}
