# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore Classic High Contrast — Nushell colour-config module
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore-classic-high-contrast · palette: steelbore-classic · variant: high-contrast (§11.1.1 accessible-mode sibling)
# Conformance: legacy six-role contract (§11.2); measured against Void Navy
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/
# Save under themes/ and source it, or point SPACECRAFT_THEME at its
# slug — see INSTALL.md.

export def main [] {
    return {
        separator: "#7FAEDC"
        leading_trailing_space_bg: "#000027"
        empty: "#7FAEDC"
        int: "#D98E32"
        filesize: "#8BE9FD"
        duration: "#D98E32"
        date: "#7FAEDC"
        range: "#D98E32"
        float: "#D98E32"
        string: "#D98E32"
        nothing: "#7FAEDC"
        binary: "#7FAEDC"
        cellpath: "#D98E32"
        record: "#7FAEDC"
        list: "#7FAEDC"
        block: "#7FAEDC"
        hints: "#7FAEDC"
        header: { fg: "#50FA7B" attr: "b" }
        row_index: { fg: "#50FA7B" attr: "b" }
        bool: { || if $in { "#50FA7B" } else { "#FF8080" } }
        search_result: { fg: "#000027" bg: "#7FAEDC" }
        shape_and: "#7FAEDC"
        shape_or: "#7FAEDC"
        shape_binary: "#7FAEDC"
        shape_block: "#7FAEDC"
        shape_bool: "#7FAEDC"
        shape_closure: "#7FAEDC"
        shape_custom: "#8BE9FD"
        shape_datetime: "#7FAEDC"
        shape_directory: "#8BE9FD"
        shape_external: "#D98E32"
        shape_external_resolved: "#50FA7B"
        shape_externalarg: "#D98E32"
        shape_filepath: "#8BE9FD"
        shape_flag: "#7FAEDC"
        shape_float: "#D98E32"
        shape_globpattern: "#8BE9FD"
        shape_int: "#D98E32"
        shape_internalcall: "#8BE9FD"
        shape_keyword: "#7FAEDC"
        shape_list: "#7FAEDC"
        shape_literal: "#7FAEDC"
        shape_match_pattern: "#7FAEDC"
        shape_matching_brackets: "#8BE9FD"
        shape_nothing: "#7FAEDC"
        shape_operator: "#7FAEDC"
        shape_pipe: "#7FAEDC"
        shape_range: "#D98E32"
        shape_record: "#7FAEDC"
        shape_redirection: "#7FAEDC"
        shape_signature: "#8BE9FD"
        shape_string: "#50FA7B"
        shape_string_interpolation: "#50FA7B"
        shape_table: "#7FAEDC"
        shape_variable: "#7FAEDC"
        shape_vardecl: "#7FAEDC"
        shape_raw_string: "#50FA7B"
        shape_garbage: { fg: "#000027" bg: "#FF8080" attr: "b" }
    }
}
