# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore Classic — Nushell colour-config module
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore-classic · palette: steelbore-classic · variant: base
# Conformance: legacy six-role contract (§11.2); measured against Void Navy
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/
# Save under themes/ and source it, or point SPACECRAFT_THEME at its
# slug — see INSTALL.md.

export def main [] {
    return {
        separator: "#4B7EB0"
        leading_trailing_space_bg: "#000027"
        empty: "#4B7EB0"
        int: "#D98E32"
        filesize: "#8BE9FD"
        duration: "#D98E32"
        date: "#4B7EB0"
        range: "#D98E32"
        float: "#D98E32"
        string: "#D98E32"
        nothing: "#4B7EB0"
        binary: "#4B7EB0"
        cellpath: "#D98E32"
        record: "#4B7EB0"
        list: "#4B7EB0"
        block: "#4B7EB0"
        hints: "#4B7EB0"
        header: { fg: "#50FA7B" attr: "b" }
        row_index: { fg: "#50FA7B" attr: "b" }
        bool: { || if $in { "#50FA7B" } else { "#FF5C5C" } }
        search_result: { fg: "#000027" bg: "#4B7EB0" }
        shape_and: "#4B7EB0"
        shape_or: "#4B7EB0"
        shape_binary: "#4B7EB0"
        shape_block: "#4B7EB0"
        shape_bool: "#4B7EB0"
        shape_closure: "#4B7EB0"
        shape_custom: "#8BE9FD"
        shape_datetime: "#4B7EB0"
        shape_directory: "#8BE9FD"
        shape_external: "#D98E32"
        shape_external_resolved: "#50FA7B"
        shape_externalarg: "#D98E32"
        shape_filepath: "#8BE9FD"
        shape_flag: "#4B7EB0"
        shape_float: "#D98E32"
        shape_globpattern: "#8BE9FD"
        shape_int: "#D98E32"
        shape_internalcall: "#8BE9FD"
        shape_keyword: "#4B7EB0"
        shape_list: "#4B7EB0"
        shape_literal: "#4B7EB0"
        shape_match_pattern: "#4B7EB0"
        shape_matching_brackets: "#8BE9FD"
        shape_nothing: "#4B7EB0"
        shape_operator: "#4B7EB0"
        shape_pipe: "#4B7EB0"
        shape_range: "#D98E32"
        shape_record: "#4B7EB0"
        shape_redirection: "#4B7EB0"
        shape_signature: "#8BE9FD"
        shape_string: "#50FA7B"
        shape_string_interpolation: "#50FA7B"
        shape_table: "#4B7EB0"
        shape_variable: "#4B7EB0"
        shape_vardecl: "#4B7EB0"
        shape_raw_string: "#50FA7B"
        shape_garbage: { fg: "#000027" bg: "#FF5C5C" attr: "b" }
    }
}
