# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore Mono — Nushell colour-config module
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore-mono · palette: steelbore-mono · variant: mono (§11.1.1, 4-bit ANSI, NO_COLOR)
# Conformance: palette-independent; defers hue to the terminal (§11.1.1)
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/
# Save under themes/ and source it, or point SPACECRAFT_THEME at its
# slug — see INSTALL.md.

export def main [] {
    return {
        separator: "blue"
        leading_trailing_space_bg: "default"
        empty: "blue"
        int: "yellow"
        filesize: "default"
        duration: "yellow"
        date: "blue"
        range: "yellow"
        float: "yellow"
        string: "default"
        nothing: "blue"
        binary: "blue"
        cellpath: "default"
        record: "blue"
        list: "blue"
        block: "blue"
        hints: "blue"
        header: { fg: "green" attr: "b" }
        row_index: { fg: "green" attr: "b" }
        bool: { || if $in { "green" } else { "red" } }
        search_result: { fg: "default" bg: "white" }
        shape_and: "blue"
        shape_or: "blue"
        shape_binary: "blue"
        shape_block: "blue"
        shape_bool: "white"
        shape_closure: "blue"
        shape_custom: "default"
        shape_datetime: "blue"
        shape_directory: "default"
        shape_external: "default"
        shape_external_resolved: "green"
        shape_externalarg: "default"
        shape_filepath: "default"
        shape_flag: "blue"
        shape_float: "yellow"
        shape_globpattern: "default"
        shape_int: "yellow"
        shape_internalcall: "default"
        shape_keyword: "white"
        shape_list: "blue"
        shape_literal: "blue"
        shape_match_pattern: "white"
        shape_matching_brackets: "default"
        shape_nothing: "blue"
        shape_operator: "blue"
        shape_pipe: "blue"
        shape_range: "yellow"
        shape_record: "blue"
        shape_redirection: "blue"
        shape_signature: "default"
        shape_string: "green"
        shape_string_interpolation: "green"
        shape_table: "blue"
        shape_variable: "white"
        shape_vardecl: "white"
        shape_raw_string: "green"
        shape_garbage: { fg: "default" bg: "red" attr: "b" }
    }
}
