# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore BlackPinkPanther — Nushell colour-config module
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore-blackpinkpanther · palette: steelbore-blackpinkpanther · variant: base
# Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/
# Save under themes/ and source it, or point SPACECRAFT_THEME at its
# slug — see INSTALL.md.

export def main [] {
    return {
        separator: "#FF46AA"
        leading_trailing_space_bg: "#2E0020"
        empty: "#FF46AA"
        int: "#FFC857"
        filesize: "#F400A1"
        duration: "#FFC857"
        date: "#FF46AA"
        range: "#FFC857"
        float: "#FFC857"
        string: "#FFFFFF"
        nothing: "#FF46AA"
        binary: "#FF46AA"
        cellpath: "#FFFFFF"
        record: "#FF46AA"
        list: "#FF46AA"
        block: "#FF46AA"
        hints: "#FF46AA"
        header: { fg: "#5BE49B" attr: "b" }
        row_index: { fg: "#5BE49B" attr: "b" }
        bool: { || if $in { "#5BE49B" } else { "#FF6B6B" } }
        search_result: { fg: "#000000" bg: "#F400A1" }
        shape_and: "#FF46AA"
        shape_or: "#FF46AA"
        shape_binary: "#FF46AA"
        shape_block: "#FF46AA"
        shape_bool: "#F400A1"
        shape_closure: "#FF46AA"
        shape_custom: "#F400A1"
        shape_datetime: "#FF46AA"
        shape_directory: "#F400A1"
        shape_external: "#FFFFFF"
        shape_external_resolved: "#5BE49B"
        shape_externalarg: "#FFFFFF"
        shape_filepath: "#F400A1"
        shape_flag: "#FF46AA"
        shape_float: "#FFC857"
        shape_globpattern: "#F400A1"
        shape_int: "#FFC857"
        shape_internalcall: "#F400A1"
        shape_keyword: "#F400A1"
        shape_list: "#FF46AA"
        shape_literal: "#FF46AA"
        shape_match_pattern: "#F400A1"
        shape_matching_brackets: "#F400A1"
        shape_nothing: "#FF46AA"
        shape_operator: "#FF46AA"
        shape_pipe: "#FF46AA"
        shape_range: "#FFC857"
        shape_record: "#FF46AA"
        shape_redirection: "#FF46AA"
        shape_signature: "#F400A1"
        shape_string: "#5BE49B"
        shape_string_interpolation: "#5BE49B"
        shape_table: "#FF46AA"
        shape_variable: "#F400A1"
        shape_vardecl: "#F400A1"
        shape_raw_string: "#5BE49B"
        shape_garbage: { fg: "#000000" bg: "#FF6B6B" attr: "b" }
    }
}
