# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore Hanzo Steel — Nushell colour-config module
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore-hanzosteel · palette: steelbore-hanzosteel · variant: base
# Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/
# Save under themes/ and source it, or point SPACECRAFT_THEME at its
# slug — see INSTALL.md.

export def main [] {
    return {
        separator: "#F4B900"
        leading_trailing_space_bg: "#1C1811"
        empty: "#F4B900"
        int: "#F7D02A"
        filesize: "#FCD612"
        duration: "#F7D02A"
        date: "#F4B900"
        range: "#F7D02A"
        float: "#F7D02A"
        string: "#F5F0E6"
        nothing: "#F4B900"
        binary: "#F4B900"
        cellpath: "#F5F0E6"
        record: "#F4B900"
        list: "#F4B900"
        block: "#F4B900"
        hints: "#F4B900"
        header: { fg: "#5BE49B" attr: "b" }
        row_index: { fg: "#5BE49B" attr: "b" }
        bool: { || if $in { "#5BE49B" } else { "#F04A44" } }
        search_result: { fg: "#000000" bg: "#FCD612" }
        shape_and: "#F4B900"
        shape_or: "#F4B900"
        shape_binary: "#F4B900"
        shape_block: "#F4B900"
        shape_bool: "#FCD612"
        shape_closure: "#F4B900"
        shape_custom: "#FCD612"
        shape_datetime: "#F4B900"
        shape_directory: "#FCD612"
        shape_external: "#F5F0E6"
        shape_external_resolved: "#5BE49B"
        shape_externalarg: "#F5F0E6"
        shape_filepath: "#FCD612"
        shape_flag: "#F4B900"
        shape_float: "#F7D02A"
        shape_globpattern: "#FCD612"
        shape_int: "#F7D02A"
        shape_internalcall: "#FCD612"
        shape_keyword: "#FCD612"
        shape_list: "#F4B900"
        shape_literal: "#F4B900"
        shape_match_pattern: "#FCD612"
        shape_matching_brackets: "#FCD612"
        shape_nothing: "#F4B900"
        shape_operator: "#F4B900"
        shape_pipe: "#F4B900"
        shape_range: "#F7D02A"
        shape_record: "#F4B900"
        shape_redirection: "#F4B900"
        shape_signature: "#FCD612"
        shape_string: "#5BE49B"
        shape_string_interpolation: "#5BE49B"
        shape_table: "#F4B900"
        shape_variable: "#FCD612"
        shape_vardecl: "#FCD612"
        shape_raw_string: "#5BE49B"
        shape_garbage: { fg: "#000000" bg: "#F04A44" attr: "b" }
    }
}
