# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore High Contrast — Nushell colour-config module
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore-high-contrast · palette: steelbore · variant: high-contrast (§11.1.1 accessible-mode sibling)
# Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/
# Save under themes/ and source it, or point SPACECRAFT_THEME at its
# slug — see INSTALL.md.

export def main [] {
    return {
        separator: "#B3A1FF"
        leading_trailing_space_bg: "#0E2A47"
        empty: "#B3A1FF"
        int: "#EE7BFF"
        filesize: "#B4FF00"
        duration: "#EE7BFF"
        date: "#B3A1FF"
        range: "#EE7BFF"
        float: "#EE7BFF"
        string: "#D9DEE5"
        nothing: "#B3A1FF"
        binary: "#B3A1FF"
        cellpath: "#D9DEE5"
        record: "#B3A1FF"
        list: "#B3A1FF"
        block: "#B3A1FF"
        hints: "#B3A1FF"
        header: { fg: "#B4FF00" attr: "b" }
        row_index: { fg: "#B4FF00" attr: "b" }
        bool: { || if $in { "#B4FF00" } else { "#FF7A7A" } }
        search_result: { fg: "#000027" bg: "#FF8A3D" }
        shape_and: "#B3A1FF"
        shape_or: "#B3A1FF"
        shape_binary: "#B3A1FF"
        shape_block: "#B3A1FF"
        shape_bool: "#FF8A3D"
        shape_closure: "#B3A1FF"
        shape_custom: "#B4FF00"
        shape_datetime: "#B3A1FF"
        shape_directory: "#B4FF00"
        shape_external: "#D9DEE5"
        shape_external_resolved: "#B4FF00"
        shape_externalarg: "#D9DEE5"
        shape_filepath: "#B4FF00"
        shape_flag: "#B3A1FF"
        shape_float: "#EE7BFF"
        shape_globpattern: "#B4FF00"
        shape_int: "#EE7BFF"
        shape_internalcall: "#B4FF00"
        shape_keyword: "#FF8A3D"
        shape_list: "#B3A1FF"
        shape_literal: "#B3A1FF"
        shape_match_pattern: "#FF8A3D"
        shape_matching_brackets: "#B4FF00"
        shape_nothing: "#B3A1FF"
        shape_operator: "#B3A1FF"
        shape_pipe: "#B3A1FF"
        shape_range: "#EE7BFF"
        shape_record: "#B3A1FF"
        shape_redirection: "#B3A1FF"
        shape_signature: "#B4FF00"
        shape_string: "#B4FF00"
        shape_string_interpolation: "#B4FF00"
        shape_table: "#B3A1FF"
        shape_variable: "#FF8A3D"
        shape_vardecl: "#FF8A3D"
        shape_raw_string: "#B4FF00"
        shape_garbage: { fg: "#000027" bg: "#FF7A7A" attr: "b" }
    }
}
