# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore NavyWhite — Nushell colour-config module
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore-navywhite · palette: steelbore-navywhite · variant: base
# Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/
# Save under themes/ and source it, or point SPACECRAFT_THEME at its
# slug — see INSTALL.md.

export def main [] {
    return {
        separator: "#1C2433"
        leading_trailing_space_bg: "#F4F3F1"
        empty: "#1C2433"
        int: "#6F4E0C"
        filesize: "#2A5580"
        duration: "#6F4E0C"
        date: "#1C2433"
        range: "#6F4E0C"
        float: "#6F4E0C"
        string: "#111827"
        nothing: "#1C2433"
        binary: "#1C2433"
        cellpath: "#111827"
        record: "#1C2433"
        list: "#1C2433"
        block: "#1C2433"
        hints: "#1C2433"
        header: { fg: "#2A6349" attr: "b" }
        row_index: { fg: "#2A6349" attr: "b" }
        bool: { || if $in { "#2A6349" } else { "#93211F" } }
        search_result: { fg: "#E7E5E0" bg: "#2A5580" }
        shape_and: "#1C2433"
        shape_or: "#1C2433"
        shape_binary: "#1C2433"
        shape_block: "#1C2433"
        shape_bool: "#2A5580"
        shape_closure: "#1C2433"
        shape_custom: "#2A5580"
        shape_datetime: "#1C2433"
        shape_directory: "#2A5580"
        shape_external: "#111827"
        shape_external_resolved: "#2A6349"
        shape_externalarg: "#111827"
        shape_filepath: "#2A5580"
        shape_flag: "#1C2433"
        shape_float: "#6F4E0C"
        shape_globpattern: "#2A5580"
        shape_int: "#6F4E0C"
        shape_internalcall: "#2A5580"
        shape_keyword: "#2A5580"
        shape_list: "#1C2433"
        shape_literal: "#1C2433"
        shape_match_pattern: "#2A5580"
        shape_matching_brackets: "#2A5580"
        shape_nothing: "#1C2433"
        shape_operator: "#1C2433"
        shape_pipe: "#1C2433"
        shape_range: "#6F4E0C"
        shape_record: "#1C2433"
        shape_redirection: "#1C2433"
        shape_signature: "#2A5580"
        shape_string: "#2A6349"
        shape_string_interpolation: "#2A6349"
        shape_table: "#1C2433"
        shape_variable: "#2A5580"
        shape_vardecl: "#2A5580"
        shape_raw_string: "#2A6349"
        shape_garbage: { fg: "#E7E5E0" bg: "#93211F" attr: "b" }
    }
}
