# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore Green High Contrast — Nushell colour-config module
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore-green-high-contrast · palette: steelbore-green · variant: high-contrast (§11.1.1 accessible-mode sibling)
# Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/
# Save under themes/ and source it, or point SPACECRAFT_THEME at its
# slug — see INSTALL.md.

export def main [] {
    return {
        separator: "#25B85F"
        leading_trailing_space_bg: "#08180C"
        empty: "#25B85F"
        int: "#FFC857"
        filesize: "#E8FFF0"
        duration: "#FFC857"
        date: "#25B85F"
        range: "#FFC857"
        float: "#FFC857"
        string: "#00FF41"
        nothing: "#25B85F"
        binary: "#25B85F"
        cellpath: "#00FF41"
        record: "#25B85F"
        list: "#25B85F"
        block: "#25B85F"
        hints: "#25B85F"
        header: { fg: "#00B81C" attr: "b" }
        row_index: { fg: "#00B81C" attr: "b" }
        bool: { || if $in { "#00B81C" } else { "#FF6B6B" } }
        search_result: { fg: "#0D0208" bg: "#E8FFF0" }
        shape_and: "#25B85F"
        shape_or: "#25B85F"
        shape_binary: "#25B85F"
        shape_block: "#25B85F"
        shape_bool: "#E8FFF0"
        shape_closure: "#25B85F"
        shape_custom: "#E8FFF0"
        shape_datetime: "#25B85F"
        shape_directory: "#E8FFF0"
        shape_external: "#00FF41"
        shape_external_resolved: "#00B81C"
        shape_externalarg: "#00FF41"
        shape_filepath: "#E8FFF0"
        shape_flag: "#25B85F"
        shape_float: "#FFC857"
        shape_globpattern: "#E8FFF0"
        shape_int: "#FFC857"
        shape_internalcall: "#E8FFF0"
        shape_keyword: "#E8FFF0"
        shape_list: "#25B85F"
        shape_literal: "#25B85F"
        shape_match_pattern: "#E8FFF0"
        shape_matching_brackets: "#E8FFF0"
        shape_nothing: "#25B85F"
        shape_operator: "#25B85F"
        shape_pipe: "#25B85F"
        shape_range: "#FFC857"
        shape_record: "#25B85F"
        shape_redirection: "#25B85F"
        shape_signature: "#E8FFF0"
        shape_string: "#00B81C"
        shape_string_interpolation: "#00B81C"
        shape_table: "#25B85F"
        shape_variable: "#E8FFF0"
        shape_vardecl: "#E8FFF0"
        shape_raw_string: "#00B81C"
        shape_garbage: { fg: "#0D0208" bg: "#FF6B6B" attr: "b" }
    }
}
