# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore Biolume — Nushell colour-config module
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore-biolume · palette: steelbore-biolume · variant: base
# Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/
# Save under themes/ and source it, or point SPACECRAFT_THEME at its
# slug — see INSTALL.md.

export def main [] {
    return {
        separator: "#00F0FF"
        leading_trailing_space_bg: "#1B2630"
        empty: "#00F0FF"
        int: "#FFC857"
        filesize: "#B6FF3B"
        duration: "#FFC857"
        date: "#00F0FF"
        range: "#FFC857"
        float: "#FFC857"
        string: "#C7D2D9"
        nothing: "#00F0FF"
        binary: "#00F0FF"
        cellpath: "#C7D2D9"
        record: "#00F0FF"
        list: "#00F0FF"
        block: "#00F0FF"
        hints: "#00F0FF"
        header: { fg: "#00B39A" attr: "b" }
        row_index: { fg: "#00B39A" attr: "b" }
        bool: { || if $in { "#00B39A" } else { "#FF6B6B" } }
        search_result: { fg: "#0C1A2B" bg: "#B6FF3B" }
        shape_and: "#00F0FF"
        shape_or: "#00F0FF"
        shape_binary: "#00F0FF"
        shape_block: "#00F0FF"
        shape_bool: "#B6FF3B"
        shape_closure: "#00F0FF"
        shape_custom: "#B6FF3B"
        shape_datetime: "#00F0FF"
        shape_directory: "#B6FF3B"
        shape_external: "#C7D2D9"
        shape_external_resolved: "#00B39A"
        shape_externalarg: "#C7D2D9"
        shape_filepath: "#B6FF3B"
        shape_flag: "#00F0FF"
        shape_float: "#FFC857"
        shape_globpattern: "#B6FF3B"
        shape_int: "#FFC857"
        shape_internalcall: "#B6FF3B"
        shape_keyword: "#B6FF3B"
        shape_list: "#00F0FF"
        shape_literal: "#00F0FF"
        shape_match_pattern: "#B6FF3B"
        shape_matching_brackets: "#B6FF3B"
        shape_nothing: "#00F0FF"
        shape_operator: "#00F0FF"
        shape_pipe: "#00F0FF"
        shape_range: "#FFC857"
        shape_record: "#00F0FF"
        shape_redirection: "#00F0FF"
        shape_signature: "#B6FF3B"
        shape_string: "#00B39A"
        shape_string_interpolation: "#00B39A"
        shape_table: "#00F0FF"
        shape_variable: "#B6FF3B"
        shape_vardecl: "#B6FF3B"
        shape_raw_string: "#00B39A"
        shape_garbage: { fg: "#0C1A2B" bg: "#FF6B6B" attr: "b" }
    }
}
