# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Tokyo Night — Nushell colour-config module
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: tokyonight · palette: tokyonight · variant: base
# Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/
# Save under themes/ and source it, or point SPACECRAFT_THEME at its
# slug — see INSTALL.md.

export def main [] {
    return {
        separator: "#BB9AF7"
        leading_trailing_space_bg: "#24283B"
        empty: "#BB9AF7"
        int: "#E0AF68"
        filesize: "#7DCFFF"
        duration: "#E0AF68"
        date: "#BB9AF7"
        range: "#E0AF68"
        float: "#E0AF68"
        string: "#C0CAF5"
        nothing: "#BB9AF7"
        binary: "#BB9AF7"
        cellpath: "#C0CAF5"
        record: "#BB9AF7"
        list: "#BB9AF7"
        block: "#BB9AF7"
        hints: "#BB9AF7"
        header: { fg: "#9ECE6A" attr: "b" }
        row_index: { fg: "#9ECE6A" attr: "b" }
        bool: { || if $in { "#9ECE6A" } else { "#F7768E" } }
        search_result: { fg: "#1A1B26" bg: "#7AA2F7" }
        shape_and: "#BB9AF7"
        shape_or: "#BB9AF7"
        shape_binary: "#BB9AF7"
        shape_block: "#BB9AF7"
        shape_bool: "#7AA2F7"
        shape_closure: "#BB9AF7"
        shape_custom: "#7DCFFF"
        shape_datetime: "#BB9AF7"
        shape_directory: "#7DCFFF"
        shape_external: "#C0CAF5"
        shape_external_resolved: "#9ECE6A"
        shape_externalarg: "#C0CAF5"
        shape_filepath: "#7DCFFF"
        shape_flag: "#BB9AF7"
        shape_float: "#E0AF68"
        shape_globpattern: "#7DCFFF"
        shape_int: "#E0AF68"
        shape_internalcall: "#7DCFFF"
        shape_keyword: "#7AA2F7"
        shape_list: "#BB9AF7"
        shape_literal: "#BB9AF7"
        shape_match_pattern: "#7AA2F7"
        shape_matching_brackets: "#7DCFFF"
        shape_nothing: "#BB9AF7"
        shape_operator: "#BB9AF7"
        shape_pipe: "#BB9AF7"
        shape_range: "#E0AF68"
        shape_record: "#BB9AF7"
        shape_redirection: "#BB9AF7"
        shape_signature: "#7DCFFF"
        shape_string: "#9ECE6A"
        shape_string_interpolation: "#9ECE6A"
        shape_table: "#BB9AF7"
        shape_variable: "#7AA2F7"
        shape_vardecl: "#7AA2F7"
        shape_raw_string: "#9ECE6A"
        shape_garbage: { fg: "#1A1B26" bg: "#F7768E" attr: "b" }
    }
}
