# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Solarized Light — Zsh prompt theme
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: solarized-light · palette: solarized-light · variant: base
# Conformance: FIDELITY PALETTE (§11.5) — reproduced verbatim, NON-CONFORMING, not adoptable as a project palette
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

# Canvas polarity (informational -- a text prompt carries no
# background fill of its own, but a companion script may branch
# on this instead of hardcoding light/dark).
typeset -g SPACECRAFT_THEME_POLARITY="light"

autoload -Uz vcs_info
precmd() { vcs_info }

# VCS branch readout -- accent, text-safe on every palette --
# plus a staged/unstaged dirty indicator (success/warning).
zstyle ':vcs_info:*' formats ' %F{#268BD2}on  %b%c%u%f'
zstyle ':vcs_info:*' actionformats ' %F{#268BD2}on  %b|%a%c%u%f'
zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:*' stagedstr ' %F{#859900}●%f'
zstyle ':vcs_info:*' unstagedstr ' %F{#B58900}●%f'

# Vi-mode command indicator (focus) -- shown only in normal
# (command) mode so insert mode stays visually quiet.
function zle-keymap-select {
    if [[ ${KEYMAP} == vicmd ]]; then
        VI_MODE_INDICATOR='%F{#2AA198}■%f '
    else
        VI_MODE_INDICATOR=''
    fi
    zle reset-prompt
}
zle -N zle-keymap-select

setopt PROMPT_SUBST

# Left: vi-mode indicator, directory (structure), VCS branch,
# exit-status glyph (success/error).
PROMPT='${VI_MODE_INDICATOR}%F{#6C71C4}%~${vcs_info_msg_0_} %(?.%F{#859900}❯.%F{#DC322F}❯) %f'

# Right: background-job count (foreground), clock (structure).
RPROMPT='%(1j.%F{#657B83}[%j]%f .)%F{#6C71C4}%*%f'
