# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore High Contrast — Zsh prompt theme
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore-high-contrast · palette: steelbore · variant: high-contrast (§11.1.1 accessible-mode sibling)
# Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

# Canvas polarity (informational -- a text prompt carries no
# background fill of its own, but a companion script may branch
# on this instead of hardcoding light/dark).
typeset -g SPACECRAFT_THEME_POLARITY="dark"

autoload -Uz vcs_info
precmd() { vcs_info }

# VCS branch readout -- accent, text-safe on every palette --
# plus a staged/unstaged dirty indicator (success/warning).
zstyle ':vcs_info:*' formats ' %F{#FF8A3D}on  %b%c%u%f'
zstyle ':vcs_info:*' actionformats ' %F{#FF8A3D}on  %b|%a%c%u%f'
zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:*' stagedstr ' %F{#B4FF00}●%f'
zstyle ':vcs_info:*' unstagedstr ' %F{#EE7BFF}●%f'

# Vi-mode command indicator (focus) -- shown only in normal
# (command) mode so insert mode stays visually quiet.
function zle-keymap-select {
    if [[ ${KEYMAP} == vicmd ]]; then
        VI_MODE_INDICATOR='%F{#B4FF00}■%f '
    else
        VI_MODE_INDICATOR=''
    fi
    zle reset-prompt
}
zle -N zle-keymap-select

setopt PROMPT_SUBST

# Left: vi-mode indicator, directory (structure), VCS branch,
# exit-status glyph (success/error).
PROMPT='${VI_MODE_INDICATOR}%F{#B3A1FF}%~${vcs_info_msg_0_} %(?.%F{#B4FF00}❯.%F{#FF7A7A}❯) %f'

# Right: background-job count (foreground), clock (structure).
RPROMPT='%(1j.%F{#D9DEE5}[%j]%f .)%F{#B3A1FF}%*%f'
