-- SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
-- SPDX-License-Identifier: GPL-3.0-or-later
--
-- Solarized Light — WezTerm color scheme
-- GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
-- Theme slug: solarized-light · palette: solarized-light · variant: base
-- Conformance: FIDELITY PALETTE (§11.5) — reproduced verbatim, NON-CONFORMING, not adoptable as a project palette
-- Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

return {
    foreground = '#657B83',
    background = '#FDF6E3',

    -- Cursor styling
    cursor_bg = '#2AA198',
    cursor_fg = '#FDF6E3',
    cursor_border = '#2AA198',

    -- Selection
    selection_fg = '#FDF6E3',
    selection_bg = '#268BD2',

    -- UI elements
    scrollbar_thumb = '#6C71C4',
    split = '#6C71C4',

    -- ANSI color palette (0-7: normal, 8-15: bright)
    ansi = {
        '#FDF6E3',
        '#DC322F',
        '#859900',
        '#B58900',
        '#6C71C4',
        '#268BD2',
        '#2AA198',
        '#657B83',
    },
    brights = {
        '#6C71C4',
        '#DC322F',
        '#859900',
        '#B58900',
        '#6C71C4',
        '#268BD2',
        '#2AA198',
        '#657B83',
    },

    -- Tab bar styling
    tab_bar = {
        background = '#EEE8D5',
        active_tab = {
            bg_color = '#268BD2',
            fg_color = '#FDF6E3',
        },
        inactive_tab = {
            bg_color = '#EEE8D5',
            fg_color = '#657B83',
        },
        inactive_tab_hover = {
            bg_color = '#EEE8D5',
            fg_color = '#268BD2',
        },
        new_tab = {
            bg_color = '#EEE8D5',
            fg_color = '#657B83',
        },
        new_tab_hover = {
            bg_color = '#EEE8D5',
            fg_color = '#268BD2',
        },
    },

    -- Visual indicators (optional)
    compose_cursor = '#B58900',
    visual_bell = '#B58900',
}
