-- SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
-- SPDX-License-Identifier: GPL-3.0-or-later
--
-- Steelbore BlackPinkPanther High Contrast — WezTerm color scheme
-- GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
-- Theme slug: steelbore-blackpinkpanther-high-contrast · palette: steelbore-blackpinkpanther · variant: high-contrast (§11.1.1 accessible-mode sibling)
-- Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
-- Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

return {
    foreground = '#FFFFFF',
    background = '#000000',

    -- Cursor styling
    cursor_bg = '#FF5FC0',
    cursor_fg = '#000000',
    cursor_border = '#FF5FC0',

    -- Selection
    selection_fg = '#000000',
    selection_bg = '#FF5FC0',

    -- UI elements
    scrollbar_thumb = '#FF70BE',
    split = '#FF70BE',

    -- ANSI color palette (0-7: normal, 8-15: bright)
    ansi = {
        '#000000',
        '#FF6B6B',
        '#5BE49B',
        '#FFC857',
        '#FF70BE',
        '#FF5FC0',
        '#FF5FC0',
        '#FFFFFF',
    },
    brights = {
        '#FF70BE',
        '#FF6B6B',
        '#5BE49B',
        '#FFC857',
        '#FF70BE',
        '#FF5FC0',
        '#FF5FC0',
        '#FFFFFF',
    },

    -- Tab bar styling
    tab_bar = {
        background = '#18000E',
        active_tab = {
            bg_color = '#FF5FC0',
            fg_color = '#000000',
        },
        inactive_tab = {
            bg_color = '#2E0020',
            fg_color = '#FFFFFF',
        },
        inactive_tab_hover = {
            bg_color = '#2E0020',
            fg_color = '#FF5FC0',
        },
        new_tab = {
            bg_color = '#2E0020',
            fg_color = '#FFFFFF',
        },
        new_tab_hover = {
            bg_color = '#2E0020',
            fg_color = '#FF5FC0',
        },
    },

    -- Visual indicators (optional)
    compose_cursor = '#FFC857',
    visual_bell = '#FFC857',
}
