-- SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
-- SPDX-License-Identifier: GPL-3.0-or-later
--
-- Steelbore BlackPinkPanther — WezTerm color scheme
-- GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
-- Theme slug: steelbore-blackpinkpanther · palette: steelbore-blackpinkpanther · variant: base
-- Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
-- Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

return {
    foreground = '#FFFFFF',
    background = '#000000',

    -- Cursor styling
    cursor_bg = '#F400A1',
    cursor_fg = '#000000',
    cursor_border = '#F400A1',

    -- Selection
    selection_fg = '#000000',
    selection_bg = '#F400A1',

    -- UI elements
    scrollbar_thumb = '#FF46AA',
    split = '#FF46AA',

    -- ANSI color palette (0-7: normal, 8-15: bright)
    ansi = {
        '#000000',
        '#FF6B6B',
        '#5BE49B',
        '#FFC857',
        '#FF46AA',
        '#F400A1',
        '#F400A1',
        '#FFFFFF',
    },
    brights = {
        '#FF46AA',
        '#FF6B6B',
        '#5BE49B',
        '#FFC857',
        '#FF46AA',
        '#F400A1',
        '#F400A1',
        '#FFFFFF',
    },

    -- Tab bar styling
    tab_bar = {
        background = '#18000E',
        active_tab = {
            bg_color = '#F400A1',
            fg_color = '#000000',
        },
        inactive_tab = {
            bg_color = '#2E0020',
            fg_color = '#FFFFFF',
        },
        inactive_tab_hover = {
            bg_color = '#2E0020',
            fg_color = '#F400A1',
        },
        new_tab = {
            bg_color = '#2E0020',
            fg_color = '#FFFFFF',
        },
        new_tab_hover = {
            bg_color = '#2E0020',
            fg_color = '#F400A1',
        },
    },

    -- Visual indicators (optional)
    compose_cursor = '#FFC857',
    visual_bell = '#FFC857',
}
