-- SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
-- SPDX-License-Identifier: GPL-3.0-or-later
--
-- Steelbore High Contrast — WezTerm color scheme
-- GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
-- Theme slug: steelbore-high-contrast · palette: steelbore · variant: high-contrast (§11.1.1 accessible-mode sibling)
-- Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
-- Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

return {
    foreground = '#D9DEE5',
    background = '#000027',

    -- Cursor styling
    cursor_bg = '#B4FF00',
    cursor_fg = '#000027',
    cursor_border = '#B4FF00',

    -- Selection
    selection_fg = '#000027',
    selection_bg = '#FF8A3D',

    -- UI elements
    scrollbar_thumb = '#B3A1FF',
    split = '#B3A1FF',

    -- ANSI color palette (0-7: normal, 8-15: bright)
    ansi = {
        '#000027',
        '#FF7A7A',
        '#B4FF00',
        '#EE7BFF',
        '#B3A1FF',
        '#FF8A3D',
        '#B4FF00',
        '#D9DEE5',
    },
    brights = {
        '#B3A1FF',
        '#FF7A7A',
        '#B4FF00',
        '#EE7BFF',
        '#B3A1FF',
        '#FF8A3D',
        '#B4FF00',
        '#D9DEE5',
    },

    -- Tab bar styling
    tab_bar = {
        background = '#0B1A12',
        active_tab = {
            bg_color = '#FF8A3D',
            fg_color = '#000027',
        },
        inactive_tab = {
            bg_color = '#0E2A47',
            fg_color = '#D9DEE5',
        },
        inactive_tab_hover = {
            bg_color = '#0E2A47',
            fg_color = '#FF8A3D',
        },
        new_tab = {
            bg_color = '#0E2A47',
            fg_color = '#D9DEE5',
        },
        new_tab_hover = {
            bg_color = '#0E2A47',
            fg_color = '#FF8A3D',
        },
    },

    -- Visual indicators (optional)
    compose_cursor = '#EE7BFF',
    visual_bell = '#EE7BFF',
}
