-- SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
-- SPDX-License-Identifier: GPL-3.0-or-later
--
-- Steelbore Green Alt — WezTerm color scheme
-- GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
-- Theme slug: steelbore-greenalt · palette: steelbore-greenalt · variant: base
-- Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
-- Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

return {
    foreground = '#D7F5E0',
    background = '#0D0208',

    -- Cursor styling
    cursor_bg = '#00FF41',
    cursor_fg = '#0D0208',
    cursor_border = '#00FF41',

    -- Selection
    selection_fg = '#0D0208',
    selection_bg = '#00FF41',

    -- UI elements
    scrollbar_thumb = '#1CA152',
    split = '#1CA152',

    -- ANSI color palette (0-7: normal, 8-15: bright)
    ansi = {
        '#0D0208',
        '#FF6B6B',
        '#00AD15',
        '#FFC857',
        '#1CA152',
        '#00FF41',
        '#00FF41',
        '#D7F5E0',
    },
    brights = {
        '#1CA152',
        '#FF6B6B',
        '#00AD15',
        '#FFC857',
        '#1CA152',
        '#00FF41',
        '#00FF41',
        '#D7F5E0',
    },

    -- Tab bar styling
    tab_bar = {
        background = '#030303',
        active_tab = {
            bg_color = '#00FF41',
            fg_color = '#0D0208',
        },
        inactive_tab = {
            bg_color = '#08180C',
            fg_color = '#D7F5E0',
        },
        inactive_tab_hover = {
            bg_color = '#08180C',
            fg_color = '#00FF41',
        },
        new_tab = {
            bg_color = '#08180C',
            fg_color = '#D7F5E0',
        },
        new_tab_hover = {
            bg_color = '#08180C',
            fg_color = '#00FF41',
        },
    },

    -- Visual indicators (optional)
    compose_cursor = '#FFC857',
    visual_bell = '#FFC857',
}
