-- SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
-- SPDX-License-Identifier: GPL-3.0-or-later
--
-- Steelbore Magnetar High Contrast — WezTerm color scheme
-- GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
-- Theme slug: steelbore-magnetar-high-contrast · palette: steelbore-magnetar · variant: high-contrast (§11.1.1 accessible-mode sibling)
-- Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
-- Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

return {
    foreground = '#FFFFFF',
    background = '#141418',

    -- Cursor styling
    cursor_bg = '#FDBBFF',
    cursor_fg = '#141418',
    cursor_border = '#FDBBFF',

    -- Selection
    selection_fg = '#141418',
    selection_bg = '#F07BFF',

    -- UI elements
    scrollbar_thumb = '#FC8AFF',
    split = '#FC8AFF',

    -- ANSI color palette (0-7: normal, 8-15: bright)
    ansi = {
        '#141418',
        '#FF8F8F',
        '#5BE49B',
        '#FFC857',
        '#FC8AFF',
        '#F07BFF',
        '#FDBBFF',
        '#FFFFFF',
    },
    brights = {
        '#FC8AFF',
        '#FF8F8F',
        '#5BE49B',
        '#FFC857',
        '#FC8AFF',
        '#F07BFF',
        '#FDBBFF',
        '#FFFFFF',
    },

    -- Tab bar styling
    tab_bar = {
        background = '#28282D',
        active_tab = {
            bg_color = '#F07BFF',
            fg_color = '#141418',
        },
        inactive_tab = {
            bg_color = '#1E1E22',
            fg_color = '#FFFFFF',
        },
        inactive_tab_hover = {
            bg_color = '#1E1E22',
            fg_color = '#F07BFF',
        },
        new_tab = {
            bg_color = '#1E1E22',
            fg_color = '#FFFFFF',
        },
        new_tab_hover = {
            bg_color = '#1E1E22',
            fg_color = '#F07BFF',
        },
    },

    -- Visual indicators (optional)
    compose_cursor = '#FFC857',
    visual_bell = '#FFC857',
}
