-- SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
-- SPDX-License-Identifier: GPL-3.0-or-later
--
-- Steelbore Blue High Contrast — WezTerm color scheme
-- GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
-- Theme slug: steelbore-blue-high-contrast · palette: steelbore-blue · variant: high-contrast (§11.1.1 accessible-mode sibling)
-- Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
-- Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

return {
    foreground = '#E6F0FF',
    background = '#0A1024',

    -- Cursor styling
    cursor_bg = '#FF8A4B',
    cursor_fg = '#0A1024',
    cursor_border = '#FF8A4B',

    -- Selection
    selection_fg = '#0A1024',
    selection_bg = '#79B4FF',

    -- UI elements
    scrollbar_thumb = '#66A3FF',
    split = '#66A3FF',

    -- ANSI color palette (0-7: normal, 8-15: bright)
    ansi = {
        '#0A1024',
        '#FF8F8F',
        '#28C76F',
        '#FFC857',
        '#66A3FF',
        '#79B4FF',
        '#FF8A4B',
        '#E6F0FF',
    },
    brights = {
        '#66A3FF',
        '#FF8F8F',
        '#28C76F',
        '#FFC857',
        '#66A3FF',
        '#79B4FF',
        '#FF8A4B',
        '#E6F0FF',
    },

    -- Tab bar styling
    tab_bar = {
        background = '#1B2436',
        active_tab = {
            bg_color = '#79B4FF',
            fg_color = '#0A1024',
        },
        inactive_tab = {
            bg_color = '#0F1728',
            fg_color = '#E6F0FF',
        },
        inactive_tab_hover = {
            bg_color = '#0F1728',
            fg_color = '#79B4FF',
        },
        new_tab = {
            bg_color = '#0F1728',
            fg_color = '#E6F0FF',
        },
        new_tab_hover = {
            bg_color = '#0F1728',
            fg_color = '#79B4FF',
        },
    },

    -- Visual indicators (optional)
    compose_cursor = '#FFC857',
    visual_bell = '#FFC857',
}
