-- SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
-- SPDX-License-Identifier: GPL-3.0-or-later
--
-- Steelbore NavyWhite — WezTerm color scheme
-- GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
-- Theme slug: steelbore-navywhite · palette: steelbore-navywhite · variant: base
-- Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
-- Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

return {
    foreground = '#111827',
    background = '#E7E5E0',

    -- Cursor styling
    cursor_bg = '#2A5580',
    cursor_fg = '#E7E5E0',
    cursor_border = '#2A5580',

    -- Selection
    selection_fg = '#E7E5E0',
    selection_bg = '#2A5580',

    -- UI elements
    scrollbar_thumb = '#1C2433',
    split = '#1C2433',

    -- ANSI color palette (0-7: normal, 8-15: bright)
    ansi = {
        '#E7E5E0',
        '#93211F',
        '#2A6349',
        '#6F4E0C',
        '#1C2433',
        '#2A5580',
        '#2A5580',
        '#111827',
    },
    brights = {
        '#1C2433',
        '#93211F',
        '#2A6349',
        '#6F4E0C',
        '#1C2433',
        '#2A5580',
        '#2A5580',
        '#111827',
    },

    -- Tab bar styling
    tab_bar = {
        background = '#D4D2CD',
        active_tab = {
            bg_color = '#2A5580',
            fg_color = '#E7E5E0',
        },
        inactive_tab = {
            bg_color = '#F4F3F1',
            fg_color = '#111827',
        },
        inactive_tab_hover = {
            bg_color = '#F4F3F1',
            fg_color = '#2A5580',
        },
        new_tab = {
            bg_color = '#F4F3F1',
            fg_color = '#111827',
        },
        new_tab_hover = {
            bg_color = '#F4F3F1',
            fg_color = '#2A5580',
        },
    },

    -- Visual indicators (optional)
    compose_cursor = '#6F4E0C',
    visual_bell = '#6F4E0C',
}
