-- SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
-- SPDX-License-Identifier: GPL-3.0-or-later
--
-- Steelbore Classic — WezTerm color scheme
-- GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
-- Theme slug: steelbore-classic · palette: steelbore-classic · variant: base
-- Conformance: legacy six-role contract (§11.2); measured against Void Navy
-- Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

return {
    foreground = '#D98E32',
    background = '#000027',

    -- Cursor styling
    cursor_bg = '#8BE9FD',
    cursor_fg = '#000027',
    cursor_border = '#8BE9FD',

    -- Selection
    selection_fg = '#000027',
    selection_bg = '#4B7EB0',

    -- UI elements
    scrollbar_thumb = '#4B7EB0',
    split = '#4B7EB0',

    -- ANSI color palette (0-7: normal, 8-15: bright)
    ansi = {
        '#000027',
        '#FF5C5C',
        '#50FA7B',
        '#D98E32',
        '#4B7EB0',
        '#4B7EB0',
        '#8BE9FD',
        '#D98E32',
    },
    brights = {
        '#4B7EB0',
        '#FF5C5C',
        '#50FA7B',
        '#D98E32',
        '#4B7EB0',
        '#4B7EB0',
        '#8BE9FD',
        '#D98E32',
    },

    -- Tab bar styling
    tab_bar = {
        background = '#000027',
        active_tab = {
            bg_color = '#4B7EB0',
            fg_color = '#000027',
        },
        inactive_tab = {
            bg_color = '#000027',
            fg_color = '#D98E32',
        },
        inactive_tab_hover = {
            bg_color = '#000027',
            fg_color = '#4B7EB0',
        },
        new_tab = {
            bg_color = '#000027',
            fg_color = '#D98E32',
        },
        new_tab_hover = {
            bg_color = '#000027',
            fg_color = '#4B7EB0',
        },
    },

    -- Visual indicators (optional)
    compose_cursor = '#D98E32',
    visual_bell = '#D98E32',
}
