-- SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
-- SPDX-License-Identifier: GPL-3.0-or-later
--
-- Steelbore NavyWhite High Contrast — WezTerm color scheme
-- GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
-- Theme slug: steelbore-navywhite-high-contrast · palette: steelbore-navywhite · variant: high-contrast (§11.1.1 accessible-mode sibling)
-- Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
-- Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

return {
    foreground = '#111827',
    background = '#E7E5E0',

    -- Cursor styling
    cursor_bg = '#1F4A73',
    cursor_fg = '#E7E5E0',
    cursor_border = '#1F4A73',

    -- Selection
    selection_fg = '#E7E5E0',
    selection_bg = '#1F4A73',

    -- UI elements
    scrollbar_thumb = '#1C2433',
    split = '#1C2433',

    -- ANSI color palette (0-7: normal, 8-15: bright)
    ansi = {
        '#E7E5E0',
        '#7E1C1A',
        '#16452F',
        '#5A3F09',
        '#1C2433',
        '#1F4A73',
        '#1F4A73',
        '#111827',
    },
    brights = {
        '#1C2433',
        '#7E1C1A',
        '#16452F',
        '#5A3F09',
        '#1C2433',
        '#1F4A73',
        '#1F4A73',
        '#111827',
    },

    -- Tab bar styling
    tab_bar = {
        background = '#D4D2CD',
        active_tab = {
            bg_color = '#1F4A73',
            fg_color = '#E7E5E0',
        },
        inactive_tab = {
            bg_color = '#F4F3F1',
            fg_color = '#111827',
        },
        inactive_tab_hover = {
            bg_color = '#F4F3F1',
            fg_color = '#1F4A73',
        },
        new_tab = {
            bg_color = '#F4F3F1',
            fg_color = '#111827',
        },
        new_tab_hover = {
            bg_color = '#F4F3F1',
            fg_color = '#1F4A73',
        },
    },

    -- Visual indicators (optional)
    compose_cursor = '#5A3F09',
    visual_bell = '#5A3F09',
}
