-- SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
-- SPDX-License-Identifier: GPL-3.0-or-later
--
-- Steelbore — WezTerm color scheme
-- GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
-- Theme slug: steelbore · palette: steelbore · variant: base
-- Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
-- Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

return {
    foreground = '#D9DEE5',
    background = '#000027',

    -- Cursor styling
    cursor_bg = '#B4FF00',
    cursor_fg = '#000027',
    cursor_border = '#B4FF00',

    -- Selection
    selection_fg = '#000027',
    selection_bg = '#FF5E00',

    -- UI elements
    scrollbar_thumb = '#8A6CFF',
    split = '#8A6CFF',

    -- ANSI color palette (0-7: normal, 8-15: bright)
    ansi = {
        '#000027',
        '#FF3B3B',
        '#B4FF00',
        '#E445FF',
        '#8A6CFF',
        '#FF5E00',
        '#B4FF00',
        '#D9DEE5',
    },
    brights = {
        '#8A6CFF',
        '#FF3B3B',
        '#B4FF00',
        '#E445FF',
        '#8A6CFF',
        '#FF5E00',
        '#B4FF00',
        '#D9DEE5',
    },

    -- Tab bar styling
    tab_bar = {
        background = '#0B1A12',
        active_tab = {
            bg_color = '#FF5E00',
            fg_color = '#000027',
        },
        inactive_tab = {
            bg_color = '#0E2A47',
            fg_color = '#D9DEE5',
        },
        inactive_tab_hover = {
            bg_color = '#0E2A47',
            fg_color = '#FF5E00',
        },
        new_tab = {
            bg_color = '#0E2A47',
            fg_color = '#D9DEE5',
        },
        new_tab_hover = {
            bg_color = '#0E2A47',
            fg_color = '#FF5E00',
        },
    },

    -- Visual indicators (optional)
    compose_cursor = '#E445FF',
    visual_bell = '#E445FF',
}
