-- SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
-- SPDX-License-Identifier: GPL-3.0-or-later
--
-- Steelbore Biolume High Contrast — WezTerm color scheme
-- GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
-- Theme slug: steelbore-biolume-high-contrast · palette: steelbore-biolume · variant: high-contrast (§11.1.1 accessible-mode sibling)
-- Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
-- Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

return {
    foreground = '#C7D2D9',
    background = '#0C1A2B',

    -- Cursor styling
    cursor_bg = '#B6FF3B',
    cursor_fg = '#0C1A2B',
    cursor_border = '#B6FF3B',

    -- Selection
    selection_fg = '#0C1A2B',
    selection_bg = '#B6FF3B',

    -- UI elements
    scrollbar_thumb = '#00F0FF',
    split = '#00F0FF',

    -- ANSI color palette (0-7: normal, 8-15: bright)
    ansi = {
        '#0C1A2B',
        '#FF8F8F',
        '#2FD3BB',
        '#FFC857',
        '#00F0FF',
        '#B6FF3B',
        '#B6FF3B',
        '#C7D2D9',
    },
    brights = {
        '#00F0FF',
        '#FF8F8F',
        '#2FD3BB',
        '#FFC857',
        '#00F0FF',
        '#B6FF3B',
        '#B6FF3B',
        '#C7D2D9',
    },

    -- Tab bar styling
    tab_bar = {
        background = '#05070A',
        active_tab = {
            bg_color = '#B6FF3B',
            fg_color = '#0C1A2B',
        },
        inactive_tab = {
            bg_color = '#1B2630',
            fg_color = '#C7D2D9',
        },
        inactive_tab_hover = {
            bg_color = '#1B2630',
            fg_color = '#B6FF3B',
        },
        new_tab = {
            bg_color = '#1B2630',
            fg_color = '#C7D2D9',
        },
        new_tab_hover = {
            bg_color = '#1B2630',
            fg_color = '#B6FF3B',
        },
    },

    -- Visual indicators (optional)
    compose_cursor = '#FFC857',
    visual_bell = '#FFC857',
}
