-- SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
-- SPDX-License-Identifier: GPL-3.0-or-later
--
-- Steelbore Hanzo Steel High Contrast — WezTerm color scheme
-- GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
-- Theme slug: steelbore-hanzosteel-high-contrast · palette: steelbore-hanzosteel · variant: high-contrast (§11.1.1 accessible-mode sibling)
-- Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
-- Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

return {
    foreground = '#F5F0E6',
    background = '#000000',

    -- Cursor styling
    cursor_bg = '#FCD612',
    cursor_fg = '#000000',
    cursor_border = '#FCD612',

    -- Selection
    selection_fg = '#000000',
    selection_bg = '#FCD612',

    -- UI elements
    scrollbar_thumb = '#F4B900',
    split = '#F4B900',

    -- ANSI color palette (0-7: normal, 8-15: bright)
    ansi = {
        '#000000',
        '#FF8F8F',
        '#5BE49B',
        '#F7D02A',
        '#F4B900',
        '#FCD612',
        '#FCD612',
        '#F5F0E6',
    },
    brights = {
        '#F4B900',
        '#FF8F8F',
        '#5BE49B',
        '#F7D02A',
        '#F4B900',
        '#FCD612',
        '#FCD612',
        '#F5F0E6',
    },

    -- Tab bar styling
    tab_bar = {
        background = '#0C0A06',
        active_tab = {
            bg_color = '#FCD612',
            fg_color = '#000000',
        },
        inactive_tab = {
            bg_color = '#1C1811',
            fg_color = '#F5F0E6',
        },
        inactive_tab_hover = {
            bg_color = '#1C1811',
            fg_color = '#FCD612',
        },
        new_tab = {
            bg_color = '#1C1811',
            fg_color = '#F5F0E6',
        },
        new_tab_hover = {
            bg_color = '#1C1811',
            fg_color = '#FCD612',
        },
    },

    -- Visual indicators (optional)
    compose_cursor = '#F7D02A',
    visual_bell = '#F7D02A',
}
