-- SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
-- SPDX-License-Identifier: GPL-3.0-or-later
--
-- Steelbore Classic High Contrast — WezTerm color scheme
-- GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
-- Theme slug: steelbore-classic-high-contrast · palette: steelbore-classic · variant: high-contrast (§11.1.1 accessible-mode sibling)
-- Conformance: legacy six-role contract (§11.2); measured against Void Navy
-- Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

return {
    foreground = '#D98E32',
    background = '#000027',

    -- Cursor styling
    cursor_bg = '#8BE9FD',
    cursor_fg = '#000027',
    cursor_border = '#8BE9FD',

    -- Selection
    selection_fg = '#000027',
    selection_bg = '#7FAEDC',

    -- UI elements
    scrollbar_thumb = '#7FAEDC',
    split = '#7FAEDC',

    -- ANSI color palette (0-7: normal, 8-15: bright)
    ansi = {
        '#000027',
        '#FF8080',
        '#50FA7B',
        '#D98E32',
        '#7FAEDC',
        '#7FAEDC',
        '#8BE9FD',
        '#D98E32',
    },
    brights = {
        '#7FAEDC',
        '#FF8080',
        '#50FA7B',
        '#D98E32',
        '#7FAEDC',
        '#7FAEDC',
        '#8BE9FD',
        '#D98E32',
    },

    -- Tab bar styling
    tab_bar = {
        background = '#000027',
        active_tab = {
            bg_color = '#7FAEDC',
            fg_color = '#000027',
        },
        inactive_tab = {
            bg_color = '#000027',
            fg_color = '#D98E32',
        },
        inactive_tab_hover = {
            bg_color = '#000027',
            fg_color = '#7FAEDC',
        },
        new_tab = {
            bg_color = '#000027',
            fg_color = '#D98E32',
        },
        new_tab_hover = {
            bg_color = '#000027',
            fg_color = '#7FAEDC',
        },
    },

    -- Visual indicators (optional)
    compose_cursor = '#D98E32',
    visual_bell = '#D98E32',
}
