-- SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
-- SPDX-License-Identifier: GPL-3.0-or-later
--
-- Tokyo Night High Contrast — WezTerm color scheme
-- GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
-- Theme slug: tokyonight-high-contrast · palette: tokyonight · variant: high-contrast (§11.1.1 accessible-mode sibling)
-- Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
-- Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

return {
    foreground = '#C0CAF5',
    background = '#1A1B26',

    -- Cursor styling
    cursor_bg = '#7DCFFF',
    cursor_fg = '#1A1B26',
    cursor_border = '#7DCFFF',

    -- Selection
    selection_fg = '#1A1B26',
    selection_bg = '#97B6F9',

    -- UI elements
    scrollbar_thumb = '#BB9AF7',
    split = '#BB9AF7',

    -- ANSI color palette (0-7: normal, 8-15: bright)
    ansi = {
        '#1A1B26',
        '#F998AA',
        '#9ECE6A',
        '#E0AF68',
        '#BB9AF7',
        '#97B6F9',
        '#7DCFFF',
        '#C0CAF5',
    },
    brights = {
        '#BB9AF7',
        '#F998AA',
        '#9ECE6A',
        '#E0AF68',
        '#BB9AF7',
        '#97B6F9',
        '#7DCFFF',
        '#C0CAF5',
    },

    -- Tab bar styling
    tab_bar = {
        background = '#16161E',
        active_tab = {
            bg_color = '#97B6F9',
            fg_color = '#1A1B26',
        },
        inactive_tab = {
            bg_color = '#24283B',
            fg_color = '#C0CAF5',
        },
        inactive_tab_hover = {
            bg_color = '#24283B',
            fg_color = '#97B6F9',
        },
        new_tab = {
            bg_color = '#24283B',
            fg_color = '#C0CAF5',
        },
        new_tab_hover = {
            bg_color = '#24283B',
            fg_color = '#97B6F9',
        },
    },

    -- Visual indicators (optional)
    compose_cursor = '#E0AF68',
    visual_bell = '#E0AF68',
}
