#!/bin/sh
# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore BlackPinkPanther High Contrast — GNOME Terminal theme (dconf profile installer)
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore-blackpinkpanther-high-contrast · palette: steelbore-blackpinkpanther · variant: high-contrast (§11.1.1 accessible-mode sibling)
# Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

# Creates the 'Steelbore BlackPinkPanther High Contrast' GNOME Terminal profile via dconf.
#
# Requires: dconf(1) and uuidgen(1). When uuidgen is missing, a
# deterministic id is derived from a checksum instead (documented
# below) so the script still runs.
#
# GNOME Terminal keys a profile by UUID, not by visible-name, so this
# script is idempotent-ish rather than idempotent: re-running it never
# edits a profile an earlier run created, it creates another one with
# the same visible-name. When that happens it warns to stderr and
# keeps going, matching the legacy installer's behaviour.
#
# GNOME Terminal's legacy profile schema has no light/dark flag of its
# own; a light theme is expressed here purely through its background
# and foreground colours, which is all VTE reads.

set -eu

PROFILE_NAME='Steelbore BlackPinkPanther High Contrast'
PROFILES_ROOT=/org/gnome/terminal/legacy/profiles:/
LIST_PATH=${PROFILES_ROOT}list

if command -v uuidgen >/dev/null 2>&1; then
    PROFILE_UUID=$(uuidgen)
else
    CHECKSUM=$(printf '%s' "$PROFILE_NAME-$$-$(date +%s%N)" | cksum | cut -d ' ' -f 1)
    PROFILE_UUID=$(printf '00000000-0000-4000-8000-%012d' "$CHECKSUM")
fi

EXISTING=$(dconf read "$LIST_PATH" 2>/dev/null || true)
EXISTING=$(printf "%s" "$EXISTING" | sed "s/^@as //")
if [ -z "$EXISTING" ]; then
    EXISTING='[]'
fi

# Warn (do not fail) if a profile with this visible-name is already
# registered -- see the idempotency note above.
for existing_uuid in $(printf "%s" "$EXISTING" | tr -d "[]" | tr "," "\n" | tr -d " '"); do
    [ -z "$existing_uuid" ] && continue
    existing_name=$(dconf read "${PROFILES_ROOT}:$existing_uuid/visible-name" 2>/dev/null || true)
    if [ "$existing_name" = "'$PROFILE_NAME'" ]; then
        printf 'warning: a GNOME Terminal profile named "%s" already exists (uuid %s); ''creating another one\n' "$PROFILE_NAME" "$existing_uuid" >&2
    fi
done

NEW_LIST=$(printf "%s" "$EXISTING" | sed "s/]/, '$PROFILE_UUID']/" | sed "s/\[, /[/")
dconf write "$LIST_PATH" "$NEW_LIST"

PROFILE_PATH="${PROFILES_ROOT}:$PROFILE_UUID/"

dconf write "${PROFILE_PATH}visible-name" "'$PROFILE_NAME'"
dconf write "${PROFILE_PATH}use-theme-colors" false
dconf write "${PROFILE_PATH}background-color" "'#000000'"
dconf write "${PROFILE_PATH}foreground-color" "'#FFFFFF'"
dconf write "${PROFILE_PATH}bold-color-same-as-fg" false
dconf write "${PROFILE_PATH}bold-color" "'#FFFFFF'"
dconf write "${PROFILE_PATH}bold-is-bright" true
dconf write "${PROFILE_PATH}cursor-colors-set" true
dconf write "${PROFILE_PATH}cursor-background-color" "'#FFFFFF'"
dconf write "${PROFILE_PATH}cursor-foreground-color" "'#000000'"
dconf write "${PROFILE_PATH}highlight-colors-set" true
dconf write "${PROFILE_PATH}highlight-background-color" "'#FF5FC0'"
dconf write "${PROFILE_PATH}highlight-foreground-color" "'#000000'"
dconf write "${PROFILE_PATH}palette" "['#000000', '#FF6B6B', '#5BE49B', '#FFC857', '#FF70BE', '#FF5FC0', '#FF5FC0', '#FFFFFF', '#FF70BE', '#FF6B6B', '#5BE49B', '#FFC857', '#FF70BE', '#FF5FC0', '#FF5FC0', '#FFFFFF']"

printf '%s profile created for GNOME Terminal.\n' "$PROFILE_NAME"
printf 'Open GNOME Terminal -> Preferences -> Profiles -> select "%s".\n' "$PROFILE_NAME"
