# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Solarized Dark — C shell (csh/tcsh) prompt theme
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: solarized-dark · palette: solarized-dark · variant: base
# Conformance: FIDELITY PALETTE (§11.5) — reproduced verbatim, NON-CONFORMING, not adoptable as a project palette
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

# Truecolor SGR sequences — set SPACECRAFT_THEME=<slug> to switch

set   red = "%{\033[38;2;220;50;47m%}"
set green = "%{\033[38;2;133;153;0m%}"
set  blue = "%{\033[38;2;108;113;196m%}"
set amber = "%{\033[38;2;38;139;210m%}"
set reset = "%{\033[0m%}"

# Prompt: [dir] [prompt char]
set prompt = "${blue}%~ ${amber}%# ${reset}"

# Clean up variables
unset red green blue amber reset
