# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore NavyWhite — C shell (csh/tcsh) prompt theme
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore-navywhite · palette: steelbore-navywhite · variant: base
# Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

# Truecolor SGR sequences — set SPACECRAFT_THEME=<slug> to switch

set   red = "%{\033[38;2;147;33;31m%}"
set green = "%{\033[38;2;42;99;73m%}"
set  blue = "%{\033[38;2;28;36;51m%}"
set amber = "%{\033[38;2;42;85;128m%}"
set reset = "%{\033[0m%}"

# Prompt: [dir] [prompt char]
set prompt = "${blue}%~ ${amber}%# ${reset}"

# Clean up variables
unset red green blue amber reset
