# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore Hanzo Steel High Contrast — C shell (csh/tcsh) prompt theme
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore-hanzosteel-high-contrast · palette: steelbore-hanzosteel · variant: high-contrast (§11.1.1 accessible-mode sibling)
# Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

# Truecolor SGR sequences — set SPACECRAFT_THEME=<slug> to switch

set   red = "%{\033[38;2;255;143;143m%}"
set green = "%{\033[38;2;91;228;155m%}"
set  blue = "%{\033[38;2;244;185;0m%}"
set amber = "%{\033[38;2;252;214;18m%}"
set reset = "%{\033[0m%}"

# Prompt: [dir] [prompt char]
set prompt = "${blue}%~ ${amber}%# ${reset}"

# Clean up variables
unset red green blue amber reset
