# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore Mono — C shell (csh/tcsh) prompt theme
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore-mono · palette: steelbore-mono · variant: mono (§11.1.1, 4-bit ANSI, NO_COLOR)
# Conformance: palette-independent; defers hue to the terminal (§11.1.1)
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

# Mono (4-bit ANSI) — follows terminal colors; set SPACECRAFT_THEME=steelbore-mono

set   red = "%{\033[31m%}"
set green = "%{\033[32m%}"
set  blue = "%{\033[34m%}"
set amber = "%{\033[97m%}"
set reset = "%{\033[0m%}"

# Prompt: [dir] [prompt char]
set prompt = "${blue}%~ ${amber}%# ${reset}"

# Clean up variables
unset red green blue amber reset
