# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore Classic High Contrast — C shell (csh/tcsh) prompt theme
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore-classic-high-contrast · palette: steelbore-classic · variant: high-contrast (§11.1.1 accessible-mode sibling)
# Conformance: legacy six-role contract (§11.2); measured against Void Navy
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

# Truecolor SGR sequences — set SPACECRAFT_THEME=<slug> to switch

set   red = "%{\033[38;2;255;128;128m%}"
set green = "%{\033[38;2;80;250;123m%}"
set  blue = "%{\033[38;2;127;174;220m%}"
set amber = "%{\033[38;2;127;174;220m%}"
set reset = "%{\033[0m%}"

# Prompt: [dir] [prompt char]
set prompt = "${blue}%~ ${amber}%# ${reset}"

# Clean up variables
unset red green blue amber reset
