# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
"""XFCE Desktop — GTK CSS theme renderer.

Generates GTK CSS themes for XFCE4 desktop environment, covering core colours,
panel styling, whisker menu, desktop icons, and comprehensive widget states.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from steelbore_themes.renderers import Archive, Target

if TYPE_CHECKING:
    from collections.abc import Mapping

    from steelbore_themes.core import Theme

_SELECTED_ICON_ALPHA = 0.6
"""Opacity for the selected-desktop-icon fill — a UI convention constant
(matching the legacy hand-written sheet's ``alpha(<accent>, 0.6)``), not a
colour value."""


def _translucent_accent(theme: Theme) -> str:
    """``rgba(r, g, b, alpha)`` over the theme's accent — never a hex.

    GTK CSS's own ``alpha()`` function only accepts a named/hex colour
    literal, not a ``@define-color`` reference, so it cannot compose with a
    role token here. ``rgba()`` accepts the token's numeric channels
    instead, matching how ``renderers/gnome.py`` composes its translucent
    ``*_shade_color`` fills rather than emitting an 8-digit hex-plus-alpha
    literal of unverified support in this engine.
    """
    r, g, b = theme.rgb("accent")
    return f"rgba({r}, {g}, {b}, {_SELECTED_ICON_ALPHA})"


def render(theme: Theme) -> Mapping[str, str]:
    """One ``themes/<slug>/gtk.css`` per theme."""
    lines = [
        theme.header_block("XFCE4 Desktop GTK CSS Theme").rstrip("\n"),
        "",
    ]
    if theme.is_light:
        lines += [
            f"/* Canvas polarity: light ({theme.slug}). GTK reads light/dark",
            "   from the desktop portal, not from this file — see tools/README.md. */",
            "",
        ]
    lines += [
        "/* --- Core Palette --- */",
        f"@define-color bg_color {theme.background};",
        f"@define-color fg_color {theme.foreground};",
        f"@define-color base_color {theme.surface_alt};",
        f"@define-color text_color {theme.foreground};",
        f"@define-color surface_color {theme.surface};",
        f"@define-color selected_bg_color {theme.accent};",
        f"@define-color selected_fg_color {theme.background};",
        f"@define-color tooltip_bg_color {theme.surface};",
        f"@define-color tooltip_fg_color {theme.foreground};",
        f"@define-color borders {theme.border};",
        f"@define-color warning_color {theme.warning};",
        f"@define-color error_color {theme.error};",
        f"@define-color success_color {theme.success};",
        f"@define-color focus_color {theme.focus};",
        f"@define-color insensitive_bg_color {theme.surface};",
        f"@define-color insensitive_fg_color {theme.structure};",
        f"@define-color link_color {theme.structure};",
        f"@define-color structure_color {theme.structure};",
        "",
        "/* --- General GTK Styling --- */",
        "window {",
        "    background-color: @bg_color;",
        "    color: @fg_color;",
        "}",
        "",
        "dialog,",
        "popover {",
        "    background-color: @surface_color;",
        "    color: @fg_color;",
        "}",
        "",
        "entry,",
        "text,",
        "textview {",
        "    background-color: @base_color;",
        "    color: @text_color;",
        "    border-color: @borders;",
        "}",
        "",
        "button {",
        "    background-color: @base_color;",
        "    color: @text_color;",
        "    border-color: @borders;",
        "}",
        "",
        "button:hover {",
        "    background-color: @selected_bg_color;",
        "    color: @selected_fg_color;",
        "}",
        "",
        "button:active,",
        "button:checked {",
        f"    background-color: {theme.text_safe_accent};",
        "    color: @selected_fg_color;",
        "}",
        "",
        "button:disabled,",
        "button:insensitive {",
        "    background-color: @insensitive_bg_color;",
        "    color: @insensitive_fg_color;",
        "}",
        "",
        "/* --- Selection and Focus --- */",
        "selection,",
        "*:selected {",
        "    background-color: @selected_bg_color;",
        "    color: @selected_fg_color;",
        "}",
        "",
        "*:focus {",
        "    outline-color: @focus_color;",
        "    border-color: @focus_color;",
        "}",
        "",
        "/* --- Tooltips --- */",
        "tooltip {",
        "    background-color: @tooltip_bg_color;",
        "    color: @tooltip_fg_color;",
        "    border-color: @borders;",
        "}",
        "",
        "/* --- XFCE Panel Specifics --- */",
        ".xfce4-panel {",
        "    background-color: @bg_color;",
        "    color: @fg_color;",
        "    font-weight: bold;",
        "}",
        "",
        ".xfce4-panel button {",
        "    background-color: transparent;",
        "    color: @fg_color;",
        "    border: none;",
        "}",
        "",
        ".xfce4-panel button:hover {",
        "    background-color: @selected_bg_color;",
        "    color: @selected_fg_color;",
        "}",
        "",
        ".xfce4-panel button:active,",
        ".xfce4-panel button:checked {",
        f"    background-color: {theme.text_safe_accent};",
        "    color: @selected_fg_color;",
        "}",
        "",
        "/* --- Whisker Menu --- */",
        "#whiskermenu-window {",
        "    background-color: @surface_color;",
        "    color: @fg_color;",
        "}",
        "",
        "#whiskermenu-window entry {",
        "    background-color: @base_color;",
        "    color: @text_color;",
        "    border: 1px solid @borders;",
        "}",
        "",
        "#whiskermenu-window entry:focus {",
        "    border-color: @focus_color;",
        "    background-color: @base_color;",
        "}",
        "",
        "#whiskermenu-window button:hover {",
        "    background-color: @selected_bg_color;",
        "    color: @selected_fg_color;",
        "}",
        "",
        "#whiskermenu-window .categories button:checked {",
        f"    background-color: {theme.text_safe_accent};",
        "    color: @selected_fg_color;",
        "    border-left: 3px solid @selected_bg_color;",
        "}",
        "",
        "/* --- Desktop Icons --- */",
        "XfdesktopIconView.view {",
        "    background-color: transparent;",
        "    color: @tooltip_fg_color;",
        "    text-shadow: 1px 1px 2px @bg_color;",
        "}",
        "",
        "XfdesktopIconView.view:selected {",
        f"    background-color: {_translucent_accent(theme)};",
        "    color: @selected_fg_color;",
        "    border-radius: 4px;",
        "}",
        "",
        "/* --- Scrollbars --- */",
        "scrollbar {",
        "    background-color: @base_color;",
        "    color: @borders;",
        "}",
        "",
        "scrollbar slider {",
        "    background-color: @borders;",
        "}",
        "",
        "scrollbar slider:hover {",
        "    background-color: @focus_color;",
        "}",
        "",
        "/* --- Taskbar --- */",
        ".tasklist button {",
        "    background-color: @base_color;",
        "    color: @text_color;",
        "    padding: 4px 8px;",
        "    border: 1px solid @borders;",
        "}",
        "",
        ".tasklist button:hover {",
        "    background-color: @selected_bg_color;",
        "    color: @selected_fg_color;",
        "}",
        "",
        ".tasklist button:active {",
        f"    background-color: {theme.text_safe_accent};",
        "    color: @selected_fg_color;",
        "}",
        "",
        "/* --- Clock and Indicators --- */",
        ".clock {",
        "    color: @fg_color;",
        "}",
        "",
        ".notification {",
        "    background-color: @tooltip_bg_color;",
        "    color: @tooltip_fg_color;",
        "    border: 1px solid @borders;",
        "}",
        "",
        "/* --- Disabled/Insensitive States --- */",
        ":disabled,",
        ":insensitive {",
        "    background-color: @insensitive_bg_color;",
        "    color: @insensitive_fg_color;",
        "}",
        "",
        "/* --- Links --- */",
        "link,",
        "*:link {",
        "    color: @link_color;",
        "}",
        "",
        "link:visited,",
        "*:visited {",
        "    color: @structure_color;",
        "}",
        "",
        "/* --- Status Colours --- */",
        ".success {",
        "    color: @success_color;",
        "}",
        "",
        ".warning {",
        "    color: @warning_color;",
        "}",
        "",
        ".error {",
        "    color: @error_color;",
        "}",
        "",
    ]
    return {f"themes/{theme.slug}/gtk.css": "\n".join(lines) + "\n"}


TARGET = Target(
    id="xfce",
    target_dir="Desktops/XFCE",
    render=render,
    supports_mono=False,
    legacy_files=("gtk.css",),
    archives=(
        Archive(
            path="Desktops/spacecraft-software-xfce.zip",
            fmt="zip",
            entries=(("themes", "themes"), ("INSTALL.md", "INSTALL.md")),
        ),
        Archive(
            path="Desktops/spacecraft-software-xfce-theme.tar.gz",
            fmt="tar.gz",
            entries=(("themes", "themes"), ("INSTALL.md", "INSTALL.md")),
        ),
    ),
    description="XFCE Desktop GTK CSS themes (include themes/<slug>/ directories)",
)
