#!/bin/sh
# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Solarized Light — Linux console (TTY) palette script
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: solarized-light · palette: solarized-light · variant: base
# Conformance: FIDELITY PALETTE (§11.5) — reproduced verbatim, NON-CONFORMING, not adoptable as a project palette
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

# Sets the Linux virtual console's 16-colour palette via the
# private "ESC ] P nc" escape (console_codes(4)). Only takes
# effect on an actual Linux console ($TERM = linux) -- a
# pseudo-terminal (xterm, tmux, SSH, ...) ignores or mishandles
# the escape, so this is a deliberate no-op there.

if [ "$TERM" = "linux" ]; then
    printf '\033]P0FDF6E3'
    printf '\033]P1DC322F'
    printf '\033]P2859900'
    printf '\033]P3B58900'
    printf '\033]P46C71C4'
    printf '\033]P5268BD2'
    printf '\033]P62AA198'
    printf '\033]P7657B83'
    printf '\033]P86C71C4'
    printf '\033]P9DC322F'
    printf '\033]PA859900'
    printf '\033]PBB58900'
    printf '\033]PC6C71C4'
    printf '\033]PD268BD2'
    printf '\033]PE2AA198'
    printf '\033]PF657B83'

    # Default foreground/background: SGR 37/40 select ANSI slots 7
    # (white -> foreground) and 0 (black -> background), which the
    # printf lines above already loaded with this theme's colours;
    # clear repaints the whole screen with them applied.
    printf '\033[37;40m'
    clear
fi
