#!/bin/sh
# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore NavyWhite High Contrast — Linux console (TTY) palette script
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore-navywhite-high-contrast · palette: steelbore-navywhite · variant: high-contrast (§11.1.1 accessible-mode sibling)
# Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

# Sets the Linux virtual console's 16-colour palette via the
# private "ESC ] P nc" escape (console_codes(4)). Only takes
# effect on an actual Linux console ($TERM = linux) -- a
# pseudo-terminal (xterm, tmux, SSH, ...) ignores or mishandles
# the escape, so this is a deliberate no-op there.

if [ "$TERM" = "linux" ]; then
    printf '\033]P0E7E5E0'
    printf '\033]P17E1C1A'
    printf '\033]P216452F'
    printf '\033]P35A3F09'
    printf '\033]P41C2433'
    printf '\033]P51F4A73'
    printf '\033]P61F4A73'
    printf '\033]P7111827'
    printf '\033]P81C2433'
    printf '\033]P97E1C1A'
    printf '\033]PA16452F'
    printf '\033]PB5A3F09'
    printf '\033]PC1C2433'
    printf '\033]PD1F4A73'
    printf '\033]PE1F4A73'
    printf '\033]PF111827'

    # Default foreground/background: SGR 37/40 select ANSI slots 7
    # (white -> foreground) and 0 (black -> background), which the
    # printf lines above already loaded with this theme's colours;
    # clear repaints the whole screen with them applied.
    printf '\033[37;40m'
    clear
fi
