#!/bin/sh
# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore Green — Linux console (TTY) palette script
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore-green · palette: steelbore-green · variant: base
# Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

# Sets the Linux virtual console's 16-colour palette via the
# private "ESC ] P nc" escape (console_codes(4)). Only takes
# effect on an actual Linux console ($TERM = linux) -- a
# pseudo-terminal (xterm, tmux, SSH, ...) ignores or mishandles
# the escape, so this is a deliberate no-op there.

if [ "$TERM" = "linux" ]; then
    printf '\033]P00D0208'
    printf '\033]P1FF6B6B'
    printf '\033]P200AD15'
    printf '\033]P3FFC857'
    printf '\033]P41CA152'
    printf '\033]P5E8FFF0'
    printf '\033]P6E8FFF0'
    printf '\033]P700FF41'
    printf '\033]P81CA152'
    printf '\033]P9FF6B6B'
    printf '\033]PA00AD15'
    printf '\033]PBFFC857'
    printf '\033]PC1CA152'
    printf '\033]PDE8FFF0'
    printf '\033]PEE8FFF0'
    printf '\033]PF00FF41'

    # Default foreground/background: SGR 37/40 select ANSI slots 7
    # (white -> foreground) and 0 (black -> background), which the
    # printf lines above already loaded with this theme's colours;
    # clear repaints the whole screen with them applied.
    printf '\033[37;40m'
    clear
fi
