#!/bin/sh
# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore — Linux console (TTY) palette script
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore · palette: steelbore · variant: base
# Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

# Sets the Linux virtual console's 16-colour palette via the
# private "ESC ] P nc" escape (console_codes(4)). Only takes
# effect on an actual Linux console ($TERM = linux) -- a
# pseudo-terminal (xterm, tmux, SSH, ...) ignores or mishandles
# the escape, so this is a deliberate no-op there.

if [ "$TERM" = "linux" ]; then
    printf '\033]P0000027'
    printf '\033]P1FF3B3B'
    printf '\033]P2B4FF00'
    printf '\033]P3E445FF'
    printf '\033]P48A6CFF'
    printf '\033]P5FF5E00'
    printf '\033]P6B4FF00'
    printf '\033]P7D9DEE5'
    printf '\033]P88A6CFF'
    printf '\033]P9FF3B3B'
    printf '\033]PAB4FF00'
    printf '\033]PBE445FF'
    printf '\033]PC8A6CFF'
    printf '\033]PDFF5E00'
    printf '\033]PEB4FF00'
    printf '\033]PFD9DEE5'

    # Default foreground/background: SGR 37/40 select ANSI slots 7
    # (white -> foreground) and 0 (black -> background), which the
    # printf lines above already loaded with this theme's colours;
    # clear repaints the whole screen with them applied.
    printf '\033[37;40m'
    clear
fi
