#!/bin/sh
# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore Mono — Linux console (TTY) palette script
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore-mono · palette: steelbore-mono · variant: mono (§11.1.1, 4-bit ANSI, NO_COLOR)
# Conformance: palette-independent; defers hue to the terminal (§11.1.1)
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

# Steelbore Mono carries no hex palette (§11.1.1). This script
# only resets terminal attributes and sets no console palette
# entries -- mono mode defers every hue to whatever 16-colour
# palette the Linux console (or the operator's own setup)
# already carries, which is what NO_COLOR sessions expect.

printf '\033[0m'
