#!/bin/sh
# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore Blue High Contrast — Linux console (TTY) palette script
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore-blue-high-contrast · palette: steelbore-blue · variant: high-contrast (§11.1.1 accessible-mode sibling)
# Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

# Sets the Linux virtual console's 16-colour palette via the
# private "ESC ] P nc" escape (console_codes(4)). Only takes
# effect on an actual Linux console ($TERM = linux) -- a
# pseudo-terminal (xterm, tmux, SSH, ...) ignores or mishandles
# the escape, so this is a deliberate no-op there.

if [ "$TERM" = "linux" ]; then
    printf '\033]P00A1024'
    printf '\033]P1FF8F8F'
    printf '\033]P228C76F'
    printf '\033]P3FFC857'
    printf '\033]P466A3FF'
    printf '\033]P579B4FF'
    printf '\033]P6FF8A4B'
    printf '\033]P7E6F0FF'
    printf '\033]P866A3FF'
    printf '\033]P9FF8F8F'
    printf '\033]PA28C76F'
    printf '\033]PBFFC857'
    printf '\033]PC66A3FF'
    printf '\033]PD79B4FF'
    printf '\033]PEFF8A4B'
    printf '\033]PFE6F0FF'

    # Default foreground/background: SGR 37/40 select ANSI slots 7
    # (white -> foreground) and 0 (black -> background), which the
    # printf lines above already loaded with this theme's colours;
    # clear repaints the whole screen with them applied.
    printf '\033[37;40m'
    clear
fi
