#!/bin/sh
# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore Magnetar High Contrast — Linux console (TTY) palette script
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore-magnetar-high-contrast · palette: steelbore-magnetar · variant: high-contrast (§11.1.1 accessible-mode sibling)
# Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

# Sets the Linux virtual console's 16-colour palette via the
# private "ESC ] P nc" escape (console_codes(4)). Only takes
# effect on an actual Linux console ($TERM = linux) -- a
# pseudo-terminal (xterm, tmux, SSH, ...) ignores or mishandles
# the escape, so this is a deliberate no-op there.

if [ "$TERM" = "linux" ]; then
    printf '\033]P0141418'
    printf '\033]P1FF8F8F'
    printf '\033]P25BE49B'
    printf '\033]P3FFC857'
    printf '\033]P4FC8AFF'
    printf '\033]P5F07BFF'
    printf '\033]P6FDBBFF'
    printf '\033]P7FFFFFF'
    printf '\033]P8FC8AFF'
    printf '\033]P9FF8F8F'
    printf '\033]PA5BE49B'
    printf '\033]PBFFC857'
    printf '\033]PCFC8AFF'
    printf '\033]PDF07BFF'
    printf '\033]PEFDBBFF'
    printf '\033]PFFFFFFF'

    # Default foreground/background: SGR 37/40 select ANSI slots 7
    # (white -> foreground) and 0 (black -> background), which the
    # printf lines above already loaded with this theme's colours;
    # clear repaints the whole screen with them applied.
    printf '\033[37;40m'
    clear
fi
