#!/bin/sh
# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore Hanzo Steel — Linux console (TTY) palette script
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore-hanzosteel · palette: steelbore-hanzosteel · variant: base
# Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

# Sets the Linux virtual console's 16-colour palette via the
# private "ESC ] P nc" escape (console_codes(4)). Only takes
# effect on an actual Linux console ($TERM = linux) -- a
# pseudo-terminal (xterm, tmux, SSH, ...) ignores or mishandles
# the escape, so this is a deliberate no-op there.

if [ "$TERM" = "linux" ]; then
    printf '\033]P0000000'
    printf '\033]P1F04A44'
    printf '\033]P25BE49B'
    printf '\033]P3F7D02A'
    printf '\033]P4F4B900'
    printf '\033]P5FCD612'
    printf '\033]P6FCD612'
    printf '\033]P7F5F0E6'
    printf '\033]P8F4B900'
    printf '\033]P9F04A44'
    printf '\033]PA5BE49B'
    printf '\033]PBF7D02A'
    printf '\033]PCF4B900'
    printf '\033]PDFCD612'
    printf '\033]PEFCD612'
    printf '\033]PFF5F0E6'

    # Default foreground/background: SGR 37/40 select ANSI slots 7
    # (white -> foreground) and 0 (black -> background), which the
    # printf lines above already loaded with this theme's colours;
    # clear repaints the whole screen with them applied.
    printf '\033[37;40m'
    clear
fi
