#!/bin/sh
# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Steelbore Classic High Contrast — Linux console (TTY) palette script
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: steelbore-classic-high-contrast · palette: steelbore-classic · variant: high-contrast (§11.1.1 accessible-mode sibling)
# Conformance: legacy six-role contract (§11.2); measured against Void Navy
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

# Sets the Linux virtual console's 16-colour palette via the
# private "ESC ] P nc" escape (console_codes(4)). Only takes
# effect on an actual Linux console ($TERM = linux) -- a
# pseudo-terminal (xterm, tmux, SSH, ...) ignores or mishandles
# the escape, so this is a deliberate no-op there.

if [ "$TERM" = "linux" ]; then
    printf '\033]P0000027'
    printf '\033]P1FF8080'
    printf '\033]P250FA7B'
    printf '\033]P3D98E32'
    printf '\033]P47FAEDC'
    printf '\033]P57FAEDC'
    printf '\033]P68BE9FD'
    printf '\033]P7D98E32'
    printf '\033]P87FAEDC'
    printf '\033]P9FF8080'
    printf '\033]PA50FA7B'
    printf '\033]PBD98E32'
    printf '\033]PC7FAEDC'
    printf '\033]PD7FAEDC'
    printf '\033]PE8BE9FD'
    printf '\033]PFD98E32'

    # Default foreground/background: SGR 37/40 select ANSI slots 7
    # (white -> foreground) and 0 (black -> background), which the
    # printf lines above already loaded with this theme's colours;
    # clear repaints the whole screen with them applied.
    printf '\033[37;40m'
    clear
fi
