#!/bin/sh
# SPDX-FileCopyrightText: 2026 Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Tokyo Night High Contrast — Linux console (TTY) palette script
# GENERATED by tools/steelbore_themes from Steelbore/steelbore.toml (palette family v3.5.0, The Steelbore Standard §11 v2.08). Do not edit by hand — regenerate.
# Theme slug: tokyonight-high-contrast · palette: tokyonight · variant: high-contrast (§11.1.1 accessible-mode sibling)
# Conformance: WCAG 2.2 AA verified against the palette canvas (§11)
# Maintainer: Mohamed Hammad <Mohamed.Hammad@SpacecraftSoftware.org> · https://Theme.SpacecraftSoftware.org/

# Sets the Linux virtual console's 16-colour palette via the
# private "ESC ] P nc" escape (console_codes(4)). Only takes
# effect on an actual Linux console ($TERM = linux) -- a
# pseudo-terminal (xterm, tmux, SSH, ...) ignores or mishandles
# the escape, so this is a deliberate no-op there.

if [ "$TERM" = "linux" ]; then
    printf '\033]P01A1B26'
    printf '\033]P1F998AA'
    printf '\033]P29ECE6A'
    printf '\033]P3E0AF68'
    printf '\033]P4BB9AF7'
    printf '\033]P597B6F9'
    printf '\033]P67DCFFF'
    printf '\033]P7C0CAF5'
    printf '\033]P8BB9AF7'
    printf '\033]P9F998AA'
    printf '\033]PA9ECE6A'
    printf '\033]PBE0AF68'
    printf '\033]PCBB9AF7'
    printf '\033]PD97B6F9'
    printf '\033]PE7DCFFF'
    printf '\033]PFC0CAF5'

    # Default foreground/background: SGR 37/40 select ANSI slots 7
    # (white -> foreground) and 0 (black -> background), which the
    # printf lines above already loaded with this theme's colours;
    # clear repaints the whole screen with them applied.
    printf '\033[37;40m'
    clear
fi
